{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "betterCommandHandler",
    "version": "v1.0.9-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.ArcLibrary",
          "module": "utils-pools",
          "version": {
            "requires": "v1.0.9-3"
          }
        }
      ],
      "files": [
        {
          "name": "betterCommandHandler-v1.0.9-3.jar",
          "url": "betterCommandHandler-v1.0.9-3.jar",
          "size": 37839,
          "sha512": "00d1a75de36470042e1c09dcc3128691debb4a98c926da58f1c58eaf50c03891d9379ddd47a876bc705d70948bf70eb334ce7f8f507dc11726294572d630e5e2",
          "sha256": "e565398d6152f7ead5b9f9fa67901ed25292f479506597c88e1df941d3dbb439",
          "sha1": "c1c563184e8006ce4060584cffb6985c8fbd20d3",
          "md5": "54dec25ad42bfd3f11f51528d3e6e847"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.ArcLibrary",
          "module": "utils-pools",
          "version": {
            "requires": "v1.0.9-3"
          }
        }
      ],
      "files": [
        {
          "name": "betterCommandHandler-v1.0.9-3.jar",
          "url": "betterCommandHandler-v1.0.9-3.jar",
          "size": 37839,
          "sha512": "00d1a75de36470042e1c09dcc3128691debb4a98c926da58f1c58eaf50c03891d9379ddd47a876bc705d70948bf70eb334ce7f8f507dc11726294572d630e5e2",
          "sha256": "e565398d6152f7ead5b9f9fa67901ed25292f479506597c88e1df941d3dbb439",
          "sha1": "c1c563184e8006ce4060584cffb6985c8fbd20d3",
          "md5": "54dec25ad42bfd3f11f51528d3e6e847"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterCommandHandler-v1.0.9-3-sources.jar",
          "url": "betterCommandHandler-v1.0.9-3-sources.jar",
          "size": 14042,
          "sha512": "9003869b4c643ad3c0db940c291328e1a02127c37e5f19935a1a8a396db433b28f3cd73420d13df01836bd17097cd106ea6034f816d79d174daae6b807f7ba37",
          "sha256": "4fd38ffc96433c8339381ef69ba338d57432b03edcc3da4b233badf410da9a7b",
          "sha1": "4677d2551dee028072839cdde9445058b6110597",
          "md5": "bb68085b44a543ec45244d772311c184"
        }
      ]
    }
  ]
}
