{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "ui-tooltips-kt",
    "version": "v1.0.9-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooltips-kt-v1.0.9-3.jar",
          "url": "ui-tooltips-kt-v1.0.9-3.jar",
          "size": 2313,
          "sha512": "b17c9a7aceaa9e1112e759fd3ef6f476519d48adbecf6311a5652f2d96b681fffd960d4034b9ea76c10484f06c0747d3f8ce6b545d5267e25dce51c49faf0bdd",
          "sha256": "b72debbb3f1928667cecd64839406133e3be7363bcd499cba2977578fb67ea7f",
          "sha1": "e34a5e175f9a8040b89590f93cd26323698f192b",
          "md5": "59385c1d3d839edbd97abe8fbdfa7b21"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.ArcLibrary",
          "module": "ui-tooltips",
          "version": {
            "requires": "v1.0.9-3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooltips-kt-v1.0.9-3.jar",
          "url": "ui-tooltips-kt-v1.0.9-3.jar",
          "size": 2313,
          "sha512": "b17c9a7aceaa9e1112e759fd3ef6f476519d48adbecf6311a5652f2d96b681fffd960d4034b9ea76c10484f06c0747d3f8ce6b545d5267e25dce51c49faf0bdd",
          "sha256": "b72debbb3f1928667cecd64839406133e3be7363bcd499cba2977578fb67ea7f",
          "sha1": "e34a5e175f9a8040b89590f93cd26323698f192b",
          "md5": "59385c1d3d839edbd97abe8fbdfa7b21"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-tooltips-kt-v1.0.9-3-sources.jar",
          "url": "ui-tooltips-kt-v1.0.9-3-sources.jar",
          "size": 963,
          "sha512": "7b89e4237459f8cb856d2e868e79e92df36313211bdc7a5ffd1e8770fa08866be1c9d3636acbb3ae9de61491ed7a23ed1ba46fc5d76902db0c2910fd138e5d3b",
          "sha256": "93a55a155c6a01171d6b3a1bca9408bd3a7cd623cab8982603ca8c239f177993",
          "sha1": "48353f71a27eecd467ceeae5f046d22ea1e6e33c",
          "md5": "9292b42643cc6c736e35ac7bb4fa0e23"
        },
        {
          "name": "ui-tooltips-kt-v1.0.9-3-sources.jar",
          "url": "ui-tooltips-kt-v1.0.9-3-sources.jar",
          "size": 963,
          "sha512": "7b89e4237459f8cb856d2e868e79e92df36313211bdc7a5ffd1e8770fa08866be1c9d3636acbb3ae9de61491ed7a23ed1ba46fc5d76902db0c2910fd138e5d3b",
          "sha256": "93a55a155c6a01171d6b3a1bca9408bd3a7cd623cab8982603ca8c239f177993",
          "sha1": "48353f71a27eecd467ceeae5f046d22ea1e6e33c",
          "md5": "9292b42643cc6c736e35ac7bb4fa0e23"
        }
      ]
    }
  ]
}
