{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "utils-pools",
    "version": "v1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "utils-pools-v1.0.5.jar",
          "url": "utils-pools-v1.0.5.jar",
          "size": 4659,
          "sha512": "af74cdb5dd3d39cc9d827b280b486e2fba3d9806d9fda31a595c766ac40d597cfc4f6022d958a4cf7b04f84554c0d9c5d313c7429c8d6382ea84591832e8b29d",
          "sha256": "3ea854089f5d139f5a36b2cdc350149bd2849afc416b5f9878a699f63613e9e4",
          "sha1": "c6271b79a22853f69b35e236569fea00e47d691b",
          "md5": "afe32606c1a83f3aba5fabf749963119"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-pools-v1.0.5.jar",
          "url": "utils-pools-v1.0.5.jar",
          "size": 4659,
          "sha512": "af74cdb5dd3d39cc9d827b280b486e2fba3d9806d9fda31a595c766ac40d597cfc4f6022d958a4cf7b04f84554c0d9c5d313c7429c8d6382ea84591832e8b29d",
          "sha256": "3ea854089f5d139f5a36b2cdc350149bd2849afc416b5f9878a699f63613e9e4",
          "sha1": "c6271b79a22853f69b35e236569fea00e47d691b",
          "md5": "afe32606c1a83f3aba5fabf749963119"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-pools-v1.0.5-sources.jar",
          "url": "utils-pools-v1.0.5-sources.jar",
          "size": 2921,
          "sha512": "74031a604f1206656432bc78449a29535d7763fb037b3e586531f895e58e4afc2385fab5fc85c61bde6248515aa0d8d5a8865f9daa6f3491c7bf4b73ebf5b460",
          "sha256": "08fd6cb0eea851df19963e9c2119641ef1f448aa56aba29ed5e581d4b2c9efb8",
          "sha1": "787e852d34e9ae197eaf07fc8330c7ad7a785012",
          "md5": "a6b7f2aae0eb6e4241cc851c7fe339b6"
        }
      ]
    }
  ]
}
