{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.MindustryModCore",
    "module": "core",
    "version": "repo-test1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-repo-test1.jar",
          "url": "core-repo-test1.jar",
          "size": 81901,
          "sha512": "87162e0c879d6f0798b3890be107e227b7ecf1b9032125619c6649194060cadd4e5a3347a6ea21b868fc27da7ac5c7e5fb533ad8a39cfeeefe70eb48cc3b1355",
          "sha256": "1f7d6d0849eb98c7c3d45e4e9ecb9896d5928058406faa9a6efd7ebbf3f74c34",
          "sha1": "0da5beee6ab1b7cd5cd8660b2d5d25a7c71acb1a",
          "md5": "2468c16cf13af9982711e13118d1601e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.MindustryModCore",
          "module": "graphics",
          "version": {
            "requires": "repo-test1"
          }
        }
      ],
      "files": [
        {
          "name": "core-repo-test1.jar",
          "url": "core-repo-test1.jar",
          "size": 81901,
          "sha512": "87162e0c879d6f0798b3890be107e227b7ecf1b9032125619c6649194060cadd4e5a3347a6ea21b868fc27da7ac5c7e5fb533ad8a39cfeeefe70eb48cc3b1355",
          "sha256": "1f7d6d0849eb98c7c3d45e4e9ecb9896d5928058406faa9a6efd7ebbf3f74c34",
          "sha1": "0da5beee6ab1b7cd5cd8660b2d5d25a7c71acb1a",
          "md5": "2468c16cf13af9982711e13118d1601e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-repo-test1-sources.jar",
          "url": "core-repo-test1-sources.jar",
          "size": 98342,
          "sha512": "9bc395197dd6c71979e227be370468af5e691efa4c6a2513ccd0f7c02bd86678c45200cbc42f307187f684443469cb38d60b13e84e6f156c6258863dee163d64",
          "sha256": "923751451efb21283e5d1c31a282dace10bd5ce12fd4dbfe0288914d91e486fa",
          "sha1": "7bad32ad7c6a212d3491c2b853b4e074b5a1c1b5",
          "md5": "5053b69af087a229f3dbd0632e7385ba"
        }
      ]
    }
  ]
}
