{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "util-compile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "util-compile-1.0.jar",
          "url": "util-compile-1.0.jar",
          "size": 3638,
          "sha512": "601c94536078f22f47dc1fe456f053a5fe5e8098825c21101ea483e92c62094ecd36e99276174ee7b077fd90b50ed4a93086530ee97c2e53f5a7d6eafb827cad",
          "sha256": "bdf13a075d7b34b90e94b8715652f48c5fcfcd03660fcd57324f0ed75b04893f",
          "sha1": "4575cffc3575e7b0c5867b1ff59feb5a97af428e",
          "md5": "159f8a2c0227cdecf791ec020ef763d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "util-compile-1.0.jar",
          "url": "util-compile-1.0.jar",
          "size": 3638,
          "sha512": "601c94536078f22f47dc1fe456f053a5fe5e8098825c21101ea483e92c62094ecd36e99276174ee7b077fd90b50ed4a93086530ee97c2e53f5a7d6eafb827cad",
          "sha256": "bdf13a075d7b34b90e94b8715652f48c5fcfcd03660fcd57324f0ed75b04893f",
          "sha1": "4575cffc3575e7b0c5867b1ff59feb5a97af428e",
          "md5": "159f8a2c0227cdecf791ec020ef763d2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "util-compile-1.0-sources.jar",
          "url": "util-compile-1.0-sources.jar",
          "size": 2229,
          "sha512": "dccf2c8fc5d056d38ad20cdc31e553b9c39ca05677b306667c4848cd2cd2a8452b809f7fd624d78e78803f4a8a91be5dfd86aee7aafc973758a97b3fb0fec6d3",
          "sha256": "6a634c036499b0517990f8a28ba5b90a502a335d01488a1343cf76bd1a575ca3",
          "sha1": "02c154ead0f60e97a9e35a42240bd4f7d355699a",
          "md5": "c9cad34d8c91b49f362c26aa6fb09fc5"
        }
      ]
    }
  ]
}
