{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.MindustryModCore",
    "module": "blocks-smartDistrubution",
    "version": "v2.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.ArcLibrary",
          "module": "graphics-extendedDraw",
          "version": {
            "requires": "v1.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "blocks-smartDistrubution-v2.0.2.jar",
          "url": "blocks-smartDistrubution-v2.0.2.jar",
          "size": 25469,
          "sha512": "383bfcc87b2c58c67c985575a1370f29b326e2fb9518fa171b9aafd21a7307ad00351ab107834728d8998055df423b11dd8631cedc9f847dab660b4bbc6cda60",
          "sha256": "c606b08106cba834bc5d53f50649da574f4615c608d49d36fd18f393df9a36d0",
          "sha1": "fb08c868176cc02a8701cf2444ccf2a93e8faa19",
          "md5": "5a5e983546a04113fddcc6744355969c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.ArcLibrary",
          "module": "graphics-extendedDraw",
          "version": {
            "requires": "v1.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "blocks-smartDistrubution-v2.0.2.jar",
          "url": "blocks-smartDistrubution-v2.0.2.jar",
          "size": 25469,
          "sha512": "383bfcc87b2c58c67c985575a1370f29b326e2fb9518fa171b9aafd21a7307ad00351ab107834728d8998055df423b11dd8631cedc9f847dab660b4bbc6cda60",
          "sha256": "c606b08106cba834bc5d53f50649da574f4615c608d49d36fd18f393df9a36d0",
          "sha1": "fb08c868176cc02a8701cf2444ccf2a93e8faa19",
          "md5": "5a5e983546a04113fddcc6744355969c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blocks-smartDistrubution-v2.0.2-sources.jar",
          "url": "blocks-smartDistrubution-v2.0.2-sources.jar",
          "size": 7465,
          "sha512": "f28e591a697ae6451d633856a0eef7bd22c03d1ccb3b9555491050f5cc9619c9bfce1f95103cfa689c3f144054700e9060a8b8f1bc02535a3327c401c6d8ab27",
          "sha256": "b583589623d9437ad0f02984fb294858788ef13a66722055191c0e311718d5a9",
          "sha1": "7a7a1037bb1a398365f4e8071b14285467580381",
          "md5": "efe1472222213c0696fe8e4c534a3f74"
        },
        {
          "name": "blocks-smartDistrubution-v2.0.2-sources.jar",
          "url": "blocks-smartDistrubution-v2.0.2-sources.jar",
          "size": 7465,
          "sha512": "f28e591a697ae6451d633856a0eef7bd22c03d1ccb3b9555491050f5cc9619c9bfce1f95103cfa689c3f144054700e9060a8b8f1bc02535a3327c401c6d8ab27",
          "sha256": "b583589623d9437ad0f02984fb294858788ef13a66722055191c0e311718d5a9",
          "sha1": "7a7a1037bb1a398365f4e8071b14285467580381",
          "md5": "efe1472222213c0696fe8e4c534a3f74"
        }
      ]
    }
  ]
}
