{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.MindustryModCore",
    "module": "annotations-mindustry",
    "version": "v2.0.3a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v146"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-mindustry-v2.0.3a.jar",
          "url": "annotations-mindustry-v2.0.3a.jar",
          "size": 1381750,
          "sha512": "7598a29e29cd64ed97510d911f02ef2ca64f2717e1574e89052b31993050cb2fd141daf2438644e3d61ac010d4c373ac8893c3a81191a8303b4dd88cec33611f",
          "sha256": "00461ed45f6e3e3ff1d85d49398bcb7490c0bbc3186074e6c8cabefd492d16d9",
          "sha1": "cb45fafb509224d0e9904763800eb92f6d611e0a",
          "md5": "ecbc3f2503839bffadc26eafe490a466"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v146"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-mindustry-v2.0.3a.jar",
          "url": "annotations-mindustry-v2.0.3a.jar",
          "size": 1381750,
          "sha512": "7598a29e29cd64ed97510d911f02ef2ca64f2717e1574e89052b31993050cb2fd141daf2438644e3d61ac010d4c373ac8893c3a81191a8303b4dd88cec33611f",
          "sha256": "00461ed45f6e3e3ff1d85d49398bcb7490c0bbc3186074e6c8cabefd492d16d9",
          "sha1": "cb45fafb509224d0e9904763800eb92f6d611e0a",
          "md5": "ecbc3f2503839bffadc26eafe490a466"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-mindustry-v2.0.3a-sources.jar",
          "url": "annotations-mindustry-v2.0.3a-sources.jar",
          "size": 11962,
          "sha512": "6daa1e57a2f852efabfea4795fd711f58f7e474e05345421ea30d7da1e017328203bd4f2bad7c6a4fb10d48bc0e38e6bd1695b51c55615f68dfe47012f69a5ca",
          "sha256": "2980e7925e857e5d41f8812194645f7890a2f991c69fdb8127b58a3759456b44",
          "sha1": "7adfffd18842e574e8b1d06e6c59ef90490d55ef",
          "md5": "eb0b24a4db69961204de392836708426"
        }
      ]
    }
  ]
}
