{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "util-post-visitor",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "util-post-visitor-unspecified.jar",
          "url": "util-post-visitor-unspecified.jar",
          "size": 10995,
          "sha512": "ba2c151045eb8adfe4718297285588cbc9b5c7e41e4045660790a8dcc93e0822e34851fe743f553e0c52c6a1638daa546881d510ec4e3dfb90d5f1728541ec24",
          "sha256": "78d903062e23159f0e3dad4924d3dd5b52e8f4a30728313968eb60f91b18af2e",
          "sha1": "6e746a26208d8ca0527ff60b2fac90ff26df906d",
          "md5": "d6f6c980533a2b4fda0b0c23b2198f03"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "util-post-visitor-unspecified.jar",
          "url": "util-post-visitor-unspecified.jar",
          "size": 10995,
          "sha512": "ba2c151045eb8adfe4718297285588cbc9b5c7e41e4045660790a8dcc93e0822e34851fe743f553e0c52c6a1638daa546881d510ec4e3dfb90d5f1728541ec24",
          "sha256": "78d903062e23159f0e3dad4924d3dd5b52e8f4a30728313968eb60f91b18af2e",
          "sha1": "6e746a26208d8ca0527ff60b2fac90ff26df906d",
          "md5": "d6f6c980533a2b4fda0b0c23b2198f03"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "util-post-visitor-unspecified-sources.jar",
          "url": "util-post-visitor-unspecified-sources.jar",
          "size": 4987,
          "sha512": "126bdc301b18a904aaf8fc47502ebdc734c504397ec502e8c440e71928b0dd91f2941181532c8af0da3a1c119361ec74a40d174b30e0bfd8134fe639478b4beb",
          "sha256": "5bff3454e7375a43d75d3b63f8f2eddddf362feb82af13c765e3690ff750a7ef",
          "sha1": "4ae248e76f73d128f386ce0abeda53c783adf816",
          "md5": "5d85cf8f9bdee3f0564d87fd3e6183eb"
        }
      ]
    }
  ]
}
