{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "util-post-visitor",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "util-post-visitor-1.0.jar",
          "url": "util-post-visitor-1.0.jar",
          "size": 10995,
          "sha512": "1b4417bb344ca4256de5d98a91894372ffe1491c8a14a9f1156bd909b5950f30fa9b3eae25a7aeba2809e2fdf1c38aeb6b5899a21b7db738e18a563c1a102d2e",
          "sha256": "4b454b0c139271b546283152a7b6c3d8805519ae578dbba53a1aadf7e1081df6",
          "sha1": "46c58826c32dcea9cccbd483f69e08193e5af515",
          "md5": "797d95010b899d62b25168048075dfa4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "util-post-visitor-1.0.jar",
          "url": "util-post-visitor-1.0.jar",
          "size": 10995,
          "sha512": "1b4417bb344ca4256de5d98a91894372ffe1491c8a14a9f1156bd909b5950f30fa9b3eae25a7aeba2809e2fdf1c38aeb6b5899a21b7db738e18a563c1a102d2e",
          "sha256": "4b454b0c139271b546283152a7b6c3d8805519ae578dbba53a1aadf7e1081df6",
          "sha1": "46c58826c32dcea9cccbd483f69e08193e5af515",
          "md5": "797d95010b899d62b25168048075dfa4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "util-post-visitor-1.0-sources.jar",
          "url": "util-post-visitor-1.0-sources.jar",
          "size": 4987,
          "sha512": "b9491ca784e81a85a1ed0c8823bcd6c545b30b6b773c8788d5a377d0c96e03107f9f29cbe6b8f1314f50da7c72900d3ae79a63901f622f8a589b2e5450007a89",
          "sha256": "c58afb386848baefe60bccb87d8f329b0fbedfce0c79d8ae765cc89a5f00cc3d",
          "sha1": "0c9ccf8c2f34dea7bc6fd1cad3f4ded875e935c3",
          "md5": "4136e7686ce3b334dccc7d0034caa8f8"
        }
      ]
    }
  ]
}
