{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "annotations-value-class",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "annotations-lombok-plugin-starter",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-value-class-unspecified.jar",
          "url": "annotations-value-class-unspecified.jar",
          "size": 8988,
          "sha512": "9a9a434b6de183813cc3f67409e675bdedd2d16adbf5cce94fbb1784eb4c2caf6b6c0334b614c0f3b82fdb7a2e9a8613581f843ffdfe50ff6a113e37f7985b01",
          "sha256": "ba7c929c519d4e8fd6c3d7dfc15aacff6b2561667e4e688586fe971c180b8882",
          "sha1": "7afafc8f96e2d2ecc7c83ab04013ef469185fb8a",
          "md5": "2647f651ca1c05391e16c81bb0526edf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "com.github.javaparser",
          "module": "javaparser-symbol-solver-core",
          "version": {
            "requires": "3.26.0"
          }
        },
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "util-classfile-metadata",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "annotations-lombok-plugin-starter",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-value-class-unspecified.jar",
          "url": "annotations-value-class-unspecified.jar",
          "size": 8988,
          "sha512": "9a9a434b6de183813cc3f67409e675bdedd2d16adbf5cce94fbb1784eb4c2caf6b6c0334b614c0f3b82fdb7a2e9a8613581f843ffdfe50ff6a113e37f7985b01",
          "sha256": "ba7c929c519d4e8fd6c3d7dfc15aacff6b2561667e4e688586fe971c180b8882",
          "sha1": "7afafc8f96e2d2ecc7c83ab04013ef469185fb8a",
          "md5": "2647f651ca1c05391e16c81bb0526edf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-value-class-unspecified-sources.jar",
          "url": "annotations-value-class-unspecified-sources.jar",
          "size": 4165,
          "sha512": "d20daa30d173e495229a91ee8b45a64ce252586ff01f8b9a4f696c60a15c95276918abd0330ba326cffd68240fa8dfd846183792b369c5aa623ca2be9c6db71a",
          "sha256": "e1b7c116db4aee649cee443fc6a7af9b59e9c6eb5d59f24240a3cfa8a12a726f",
          "sha1": "29dea606e03fd3efc9f3f6f9d44d5056271d9e22",
          "md5": "c2e744cd88995bce244cd8bd56cda260"
        }
      ]
    }
  ]
}
