{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "analytics-method-return",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "analytics-object-creation",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "analytics-method-return-unspecified.jar",
          "url": "analytics-method-return-unspecified.jar",
          "size": 8609,
          "sha512": "9b810cee3303796ab9d0de6b3c8e71d96686c0ac96962f3922f2171ae084908a2a288f949f142d3df0f17ec2d7192b221b143869fff9a9dafb7e1caf2e7fa543",
          "sha256": "47d67b919dd4cc19934bee61921d57e18c29e92749b09a06b071d6434490ae15",
          "sha1": "e437105357c2ecae964376954b650e52c78feb0a",
          "md5": "0f64c68be0567a10dd4a18ad2ecc9ac0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "analytics-object-creation",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "analytics-method-return-unspecified.jar",
          "url": "analytics-method-return-unspecified.jar",
          "size": 8609,
          "sha512": "9b810cee3303796ab9d0de6b3c8e71d96686c0ac96962f3922f2171ae084908a2a288f949f142d3df0f17ec2d7192b221b143869fff9a9dafb7e1caf2e7fa543",
          "sha256": "47d67b919dd4cc19934bee61921d57e18c29e92749b09a06b071d6434490ae15",
          "sha1": "e437105357c2ecae964376954b650e52c78feb0a",
          "md5": "0f64c68be0567a10dd4a18ad2ecc9ac0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "analytics-method-return-unspecified-sources.jar",
          "url": "analytics-method-return-unspecified-sources.jar",
          "size": 3492,
          "sha512": "e34eee3cd0c5553cbc9c7088f17eea22a2147bbb4c3668f5ce664c6b1f1ae2f1aee8ee6dcb6eab2f774fecc60a064fb15599385b44e1c433d63d4460a19a9543",
          "sha256": "83cc19ce83d19bbdb43bc179d3418a6501be0d41416ece3243f3d525d77b2eb0",
          "sha1": "ea71f53819da78ab8cb38aa1a2eee6eeffddff12",
          "md5": "dc3bc090dd31c06001787b588acb03c2"
        }
      ]
    }
  ]
}
