{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.opus4j",
    "module": "opus4j",
    "version": "X",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "opus4j-X.jar",
          "url": "opus4j-X.jar",
          "size": 1463749,
          "sha512": "f904c1a56a11d3ed69c653f355bf84933f546da839ff10163493259b5324c552f5ae0be80d4e20aa7d4a7a55dcd84714006de8118ddd7f8cae4c8180c444c746",
          "sha256": "c455d30330acc668441597c1d860589912d0af7c28ac9946489e83a33b240d2c",
          "sha1": "593bcc15121948dd47dcbffb7fbdfc5b3929b439",
          "md5": "3cf30117cd95411248eda5822ebf3f33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.maxhenkel.native-utils",
          "module": "native-utils",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "opus4j-X.jar",
          "url": "opus4j-X.jar",
          "size": 1463749,
          "sha512": "f904c1a56a11d3ed69c653f355bf84933f546da839ff10163493259b5324c552f5ae0be80d4e20aa7d4a7a55dcd84714006de8118ddd7f8cae4c8180c444c746",
          "sha256": "c455d30330acc668441597c1d860589912d0af7c28ac9946489e83a33b240d2c",
          "sha1": "593bcc15121948dd47dcbffb7fbdfc5b3929b439",
          "md5": "3cf30117cd95411248eda5822ebf3f33"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opus4j-X.jar",
          "url": "opus4j-X.jar",
          "size": 1463749,
          "sha512": "f904c1a56a11d3ed69c653f355bf84933f546da839ff10163493259b5324c552f5ae0be80d4e20aa7d4a7a55dcd84714006de8118ddd7f8cae4c8180c444c746",
          "sha256": "c455d30330acc668441597c1d860589912d0af7c28ac9946489e83a33b240d2c",
          "sha1": "593bcc15121948dd47dcbffb7fbdfc5b3929b439",
          "md5": "3cf30117cd95411248eda5822ebf3f33"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opus4j-X-sources.jar",
          "url": "opus4j-X-sources.jar",
          "size": 4213,
          "sha512": "1bde7eedc9e50de88cf8dc51198796312c1cc0d77572b91acae96c266b25589c1c7a1c77e72bb6b0f1e779abd1d1169b4abcd84102194b37783fc82002b3c493",
          "sha256": "28637047f06139dcbf71c5ebc10ee615a59f148895b9c748dcf03418b000e675",
          "sha1": "43086175bfe9100753e064672a8225a07b190458",
          "md5": "b1f548aea498041c2fa7651ceb3996e4"
        }
      ]
    }
  ]
}
