{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.MindustryModCore",
    "module": "plugins",
    "version": "repo-test1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugins-repo-test1.jar",
          "url": "plugins-repo-test1.jar",
          "size": 3214,
          "sha512": "4e835ac8a26f594ac7edad853d1384fbbc512fc81b86a7a2b1a8647be95cb484b7137825f994aebf09c638862a166148f679df7a8e0b9f1de0b837ec6b8ddd84",
          "sha256": "09658dd5361568b8f3e61657d75ffbbf08022a094504aa0336619ca4ed65f4a8",
          "sha1": "eb8e3c34552b8eed6e22119a6ed941dd0dcf2c3b",
          "md5": "f46eb4a6f67fb4e91225311398b56249"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugins-repo-test1.jar",
          "url": "plugins-repo-test1.jar",
          "size": 3214,
          "sha512": "4e835ac8a26f594ac7edad853d1384fbbc512fc81b86a7a2b1a8647be95cb484b7137825f994aebf09c638862a166148f679df7a8e0b9f1de0b837ec6b8ddd84",
          "sha256": "09658dd5361568b8f3e61657d75ffbbf08022a094504aa0336619ca4ed65f4a8",
          "sha1": "eb8e3c34552b8eed6e22119a6ed941dd0dcf2c3b",
          "md5": "f46eb4a6f67fb4e91225311398b56249"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugins-repo-test1-sources.jar",
          "url": "plugins-repo-test1-sources.jar",
          "size": 1529,
          "sha512": "973f0db610ebff64797c855e9211c508cf6de0262dc5a57b90166885916d64399bd0feb13c23bb2ed84fc926693960fdc10a5150c6a34b178c06a3e7a9ad4cc2",
          "sha256": "8784f22d80badca360185e8d893bb93fca6c981d8fd0873ec18e2b3d0744204e",
          "sha1": "30ed7164f72aa887c288bc1edbd19d03be0e391d",
          "md5": "f1023f475875a7a32204583ffdbde3ba"
        }
      ]
    }
  ]
}
