{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "transformation-core",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "transformation-core-unspecified.jar",
          "url": "transformation-core-unspecified.jar",
          "size": 14678,
          "sha512": "593011488ca6200b2a7fa939df9a822e754de47c61d2ebf440708f1b1ecfb7cf0465ebbe97bd0617b5a59cdc3d6687492074e3ca3ff9e2adb86ef23ba2b84550",
          "sha256": "80dd3006117c708d5b6698f94699c5d8f8d1ed142aa0ff136da0edb64bd07bba",
          "sha1": "25eecff68203a11a5861ea13df83f43a00805423",
          "md5": "fb80d996593a2e97c54d854c56c4f5dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "transformation-core-unspecified.jar",
          "url": "transformation-core-unspecified.jar",
          "size": 14678,
          "sha512": "593011488ca6200b2a7fa939df9a822e754de47c61d2ebf440708f1b1ecfb7cf0465ebbe97bd0617b5a59cdc3d6687492074e3ca3ff9e2adb86ef23ba2b84550",
          "sha256": "80dd3006117c708d5b6698f94699c5d8f8d1ed142aa0ff136da0edb64bd07bba",
          "sha1": "25eecff68203a11a5861ea13df83f43a00805423",
          "md5": "fb80d996593a2e97c54d854c56c4f5dd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "transformation-core-unspecified-sources.jar",
          "url": "transformation-core-unspecified-sources.jar",
          "size": 6197,
          "sha512": "e74275b9bd0efcee25d9b3de3d9921341be8bdee0440bfa31a6661a17b4b5212596e19a28eeac86259204fa733c3acf54847e7c13bf0196807353e91587e583e",
          "sha256": "e0379f18282198c482a8bbc49db1572456f6a2b279688ada6cb4615f96652939",
          "sha1": "16ecf872592d6efa6d32f6798e7120445e6be371",
          "md5": "90498f4444800eaa39761496ebdcc632"
        }
      ]
    }
  ]
}
