{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "ui-listeners",
    "version": "v1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-listeners-v1.0.5.jar",
          "url": "ui-listeners-v1.0.5.jar",
          "size": 4781,
          "sha512": "efd4b60b9af8bc0494c5c4c5e62a506576570681a77e0438109b76437bbaa21ae5334b9850df33bbf00c3006308d79620569e75b1bf44192f8d2afa02d6aa2a4",
          "sha256": "ae02c8e7d3d2cbe0db84082385e06a2c76925702a523f3a3e3d3256f64822288",
          "sha1": "0730b36e7b560c3fa7d60b32a07bf32650363be8",
          "md5": "19464d7eea879bdc815703ad4d2b6668"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-listeners-v1.0.5.jar",
          "url": "ui-listeners-v1.0.5.jar",
          "size": 4781,
          "sha512": "efd4b60b9af8bc0494c5c4c5e62a506576570681a77e0438109b76437bbaa21ae5334b9850df33bbf00c3006308d79620569e75b1bf44192f8d2afa02d6aa2a4",
          "sha256": "ae02c8e7d3d2cbe0db84082385e06a2c76925702a523f3a3e3d3256f64822288",
          "sha1": "0730b36e7b560c3fa7d60b32a07bf32650363be8",
          "md5": "19464d7eea879bdc815703ad4d2b6668"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-listeners-v1.0.5-sources.jar",
          "url": "ui-listeners-v1.0.5-sources.jar",
          "size": 1908,
          "sha512": "01cc3d8ea8efb7b163f2d47b6604bcc3996a95523e74dc7798ab520125da9f1e7de63507c513e439ebf8f3e201dd9e69f756dcf1ee27ede0cb52d318caf7ca17",
          "sha256": "48fe78b931095458cfe0ee4c00963197e69b6ae8a1a53fbdf5788e769930fd60",
          "sha1": "24dce09e50d9f11fff6ba9916ed91cfe908990bf",
          "md5": "8a958a29e8641de76f3ca5a8f7e53f41"
        }
      ]
    }
  ]
}
