{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "util-method",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "util-method-unspecified.jar",
          "url": "util-method-unspecified.jar",
          "size": 3443,
          "sha512": "e7c3545b332ed32cefd38e5def04146ed1649b796447bb57b736398b936e4d5ad721398611867d8b34fdb9844cd52e69aebf9dba47562ccb5fe5a50fd0e5808f",
          "sha256": "1a81b9d9a208f9a1c0b73518bfdcaed145151821655aabde2f0dbe11d95547d5",
          "sha1": "dc49e1204bb1ae546c848d7d7b5cb8edd9752885",
          "md5": "0f9bd393a74c6e57ec02c7bd3b8df22d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "util-method-unspecified.jar",
          "url": "util-method-unspecified.jar",
          "size": 3443,
          "sha512": "e7c3545b332ed32cefd38e5def04146ed1649b796447bb57b736398b936e4d5ad721398611867d8b34fdb9844cd52e69aebf9dba47562ccb5fe5a50fd0e5808f",
          "sha256": "1a81b9d9a208f9a1c0b73518bfdcaed145151821655aabde2f0dbe11d95547d5",
          "sha1": "dc49e1204bb1ae546c848d7d7b5cb8edd9752885",
          "md5": "0f9bd393a74c6e57ec02c7bd3b8df22d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "util-method-unspecified-sources.jar",
          "url": "util-method-unspecified-sources.jar",
          "size": 1928,
          "sha512": "38c9d13862149e0e083e5f69a137dd55aa5ff194deb5ae5dca2fad5f6008cda1047a3473d4c4a87c01733ed27a9206f608e829f3ffea99588838ee6be39420d9",
          "sha256": "5ea7421e4ddff04737fbf9b77bda20637aac4fd40956370083cf73fe98a4445b",
          "sha1": "93d5f1a736cfe3400fd9112c8e8e2331eda5d503",
          "md5": "5ae7f0970a196eaa23178ae26b59aeb5"
        }
      ]
    }
  ]
}
