{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "util-method",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "util-method-unspecified.jar",
          "url": "util-method-unspecified.jar",
          "size": 3443,
          "sha512": "7a86e36213efd5d79bbb2718a17ce293046c969b6b1d33790535b5b828c1991f6b880a20cf39f1c443392c22cd7a9714a1c02e22e341c18c02eb79432d22bf3e",
          "sha256": "4138b5806911f5a5225b1daa2f57f72c69b96b448e31f6f61e480a952846a467",
          "sha1": "ee80b51295f1358cccf9a69dba527a7481acf9b3",
          "md5": "bc220e2d1a00f1aa443a673eee786c52"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "util-method-unspecified.jar",
          "url": "util-method-unspecified.jar",
          "size": 3443,
          "sha512": "7a86e36213efd5d79bbb2718a17ce293046c969b6b1d33790535b5b828c1991f6b880a20cf39f1c443392c22cd7a9714a1c02e22e341c18c02eb79432d22bf3e",
          "sha256": "4138b5806911f5a5225b1daa2f57f72c69b96b448e31f6f61e480a952846a467",
          "sha1": "ee80b51295f1358cccf9a69dba527a7481acf9b3",
          "md5": "bc220e2d1a00f1aa443a673eee786c52"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "util-method-unspecified-sources.jar",
          "url": "util-method-unspecified-sources.jar",
          "size": 1928,
          "sha512": "033615657a76cb2708824eb7b850df30b538c9d8538af39336cdd78fbb43d7f4a48dc0645eb8ffe6708dda42093849ba60371af9b66c59b8baf74504bf29db37",
          "sha256": "9db9312aab563a9cc47361d4f5b86a25ae802a8b55ec5aca90e5032021bc6ed3",
          "sha1": "3870ae24581619a023f4ed126595e78e07779e4c",
          "md5": "57dfb71ccad9e20d8360f91c5f7e603e"
        }
      ]
    }
  ]
}
