{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "utils-entries",
    "version": "v1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "utils-entries-v1.0.5.jar",
          "url": "utils-entries-v1.0.5.jar",
          "size": 2563,
          "sha512": "4a01fe4882f840a9fd5004171aaa51d69a5bd8c5812b3dc772c21e52bd0752fbf2ece988bb70edb1a311656713d7a3993cfbb29c39c335672bbcf98f3c5e94af",
          "sha256": "c48fd8b8198352d83fffac7fa58725cd2cfec08f54647bd70608a5db4dc8ebb2",
          "sha1": "13a8b0637fb9caa735aacf66a79ae4ad6eb9a44c",
          "md5": "ec39c5d12e236b2d65f670ebe7188870"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-entries-v1.0.5.jar",
          "url": "utils-entries-v1.0.5.jar",
          "size": 2563,
          "sha512": "4a01fe4882f840a9fd5004171aaa51d69a5bd8c5812b3dc772c21e52bd0752fbf2ece988bb70edb1a311656713d7a3993cfbb29c39c335672bbcf98f3c5e94af",
          "sha256": "c48fd8b8198352d83fffac7fa58725cd2cfec08f54647bd70608a5db4dc8ebb2",
          "sha1": "13a8b0637fb9caa735aacf66a79ae4ad6eb9a44c",
          "md5": "ec39c5d12e236b2d65f670ebe7188870"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-entries-v1.0.5-sources.jar",
          "url": "utils-entries-v1.0.5-sources.jar",
          "size": 1292,
          "sha512": "bd58400a7cb30ebe4dacb76c74d470e8f128bed85d948397cd1339707d959c386f4ac21d5702698ec37c392c00d5778ef616702f467dd11678705a2f0908215d",
          "sha256": "932f779edf145cd87ad39fd6f8605e4b225f76d52b7eb6a741ac34f3c47bc249",
          "sha1": "efd4246091e5e1c0b28ff5b3956eefb9ae4d60a2",
          "md5": "a194c33bfdeb340b305ab5a2dcadc425"
        }
      ]
    }
  ]
}
