{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "annotations-method-bytecode",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "annotations-lombok-plugin-starter",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "util-post-visitor",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "util-compile",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "util-node",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "util-classfile-metadata",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-method-bytecode-unspecified.jar",
          "url": "annotations-method-bytecode-unspecified.jar",
          "size": 20292,
          "sha512": "3875bd414ec63f233430bfe6d51dacc3eb97beba58c1501044d6f98646768267f6fd4c4c23bbe51337c9396ee98b75edd3c82c8989514b37b9c53963f25cdce6",
          "sha256": "9bd96e5b2fb438284794bba7f8cc2ba060a3ca4723e7a37c9d69af5348e7236c",
          "sha1": "e9dc783adc322e703195e0b69ddc8ff86fb25831",
          "md5": "d233e88e9a83aea21e4f34148c0dbc9d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "com.github.javaparser",
          "module": "javaparser-symbol-solver-core",
          "version": {
            "requires": "3.26.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "annotations-lombok-plugin-starter",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "util-post-visitor",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "util-compile",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "util-node",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "util-classfile-metadata",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-method-bytecode-unspecified.jar",
          "url": "annotations-method-bytecode-unspecified.jar",
          "size": 20292,
          "sha512": "3875bd414ec63f233430bfe6d51dacc3eb97beba58c1501044d6f98646768267f6fd4c4c23bbe51337c9396ee98b75edd3c82c8989514b37b9c53963f25cdce6",
          "sha256": "9bd96e5b2fb438284794bba7f8cc2ba060a3ca4723e7a37c9d69af5348e7236c",
          "sha1": "e9dc783adc322e703195e0b69ddc8ff86fb25831",
          "md5": "d233e88e9a83aea21e4f34148c0dbc9d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-method-bytecode-unspecified-sources.jar",
          "url": "annotations-method-bytecode-unspecified-sources.jar",
          "size": 11233,
          "sha512": "555a9491b64e0b8a9d6750114b465339fccb5095433fe2db565ad1506a1f66a9c44f7c8b7f51ed3a9c7d792fb8e02fcdf9dc68333f56f58464e71ebc0b3d9316",
          "sha256": "04302174e6ed66c139d66cefa5099b184c3c15b0291b5608341452ecc61bbbca",
          "sha1": "0256239d327be75e9a17ecd3184a33e01fc48def",
          "md5": "d49b63c31f14ba1b20c43e874bc20769"
        }
      ]
    }
  ]
}
