{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "ui-defaults",
    "version": "v1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-defaults-v1.0.5.jar",
          "url": "ui-defaults-v1.0.5.jar",
          "size": 2732,
          "sha512": "0ae9e65063cf1fdabc4569a5c0b15c218fbc6a1ebcd561ac03625a4acab315a65137aaa2145bc163ff4a12df61366caaca333a1536807d3f3b85a767533a2037",
          "sha256": "cdb4a5b778b67570a9251b92de59315b017a14fee2efef865d55315529f67259",
          "sha1": "0cfb9cbcdf790678d0e81f25fc30011e3e051b00",
          "md5": "9cc5379ebd6ff683fd67f8dce0dc97b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-defaults-v1.0.5.jar",
          "url": "ui-defaults-v1.0.5.jar",
          "size": 2732,
          "sha512": "0ae9e65063cf1fdabc4569a5c0b15c218fbc6a1ebcd561ac03625a4acab315a65137aaa2145bc163ff4a12df61366caaca333a1536807d3f3b85a767533a2037",
          "sha256": "cdb4a5b778b67570a9251b92de59315b017a14fee2efef865d55315529f67259",
          "sha1": "0cfb9cbcdf790678d0e81f25fc30011e3e051b00",
          "md5": "9cc5379ebd6ff683fd67f8dce0dc97b5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-defaults-v1.0.5-sources.jar",
          "url": "ui-defaults-v1.0.5-sources.jar",
          "size": 1306,
          "sha512": "dbedb6cd053ca3961661268fde7d1a9635470e55b1f8c9aa9830bf952f929e577064acdce0640a0e17d76c132825e03b7d21e063b34323300736828d7283b837",
          "sha256": "65282ccae2c447cb97f8e25ee44ad261f624d6a9ccef1347aeb6d9b648cf267d",
          "sha1": "2e1fa5f30d3f5c4d2e124851ed672e944531692c",
          "md5": "c44ba354514266e8de0c3acbd2f6aaab"
        }
      ]
    }
  ]
}
