{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "util-loader",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "util-loader-unspecified.jar",
          "url": "util-loader-unspecified.jar",
          "size": 1882,
          "sha512": "63d0efbb2d7b7219f4775686e30cd31bc0b5b899ff2da4b607d9f8217e9daa041300af53f0834038d629dceaf7bbc94d6053abb4931d2a8df7524ee1b9185c29",
          "sha256": "0da85524aceabec37fe036018211ceafcdd65d326ac7857e80e6102cff93fafd",
          "sha1": "06be85d4c498a11e752fee85a414ee1c826e582e",
          "md5": "24541ff713c69cb99d3f46a8c0f798a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "util-loader-unspecified.jar",
          "url": "util-loader-unspecified.jar",
          "size": 1882,
          "sha512": "63d0efbb2d7b7219f4775686e30cd31bc0b5b899ff2da4b607d9f8217e9daa041300af53f0834038d629dceaf7bbc94d6053abb4931d2a8df7524ee1b9185c29",
          "sha256": "0da85524aceabec37fe036018211ceafcdd65d326ac7857e80e6102cff93fafd",
          "sha1": "06be85d4c498a11e752fee85a414ee1c826e582e",
          "md5": "24541ff713c69cb99d3f46a8c0f798a7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "util-loader-unspecified-sources.jar",
          "url": "util-loader-unspecified-sources.jar",
          "size": 1276,
          "sha512": "500cad9b7712b814e7133d731934433899be537d8c91216dab46e58cbe99f81f1f2927609f60b76e87da4a69489b5544f309b3f9c364a58513dfe0e8e84cf186",
          "sha256": "925284ba48f49497fea10bc9d2b0bbc9b43e5774055aed18a3c4e9ee4df4574d",
          "sha1": "3c5979a54adfea8b9082041dc016586bd2af5981",
          "md5": "fd93dfbcf939f7bc7d297df4c5a4dbb1"
        }
      ]
    }
  ]
}
