{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.MindustryModCore",
    "module": "blocks-smartDistrubution",
    "version": "v2.0.3a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.ArcLibrary",
          "module": "graphics-extendedDraw",
          "version": {
            "requires": "v1.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "blocks-smartDistrubution-v2.0.3a.jar",
          "url": "blocks-smartDistrubution-v2.0.3a.jar",
          "size": 25469,
          "sha512": "5da60abf6f30bbd6060c3921ab9a5525191fc7b93e9e307f3b87f96a7768dc601cc5ec021ffeeda2f049a07a52c418a34dc04955c9617615503e78c3d206cff9",
          "sha256": "354940f05d55835b561302c67e9e088302bbad93a14e209b1cdc59b8b5871bba",
          "sha1": "b0ed6e19a1e9c1fc1361a678e86a1071a98c4941",
          "md5": "5d5955cfb1186f2fb4d263cd6a71400c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.ArcLibrary",
          "module": "graphics-extendedDraw",
          "version": {
            "requires": "v1.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "blocks-smartDistrubution-v2.0.3a.jar",
          "url": "blocks-smartDistrubution-v2.0.3a.jar",
          "size": 25469,
          "sha512": "5da60abf6f30bbd6060c3921ab9a5525191fc7b93e9e307f3b87f96a7768dc601cc5ec021ffeeda2f049a07a52c418a34dc04955c9617615503e78c3d206cff9",
          "sha256": "354940f05d55835b561302c67e9e088302bbad93a14e209b1cdc59b8b5871bba",
          "sha1": "b0ed6e19a1e9c1fc1361a678e86a1071a98c4941",
          "md5": "5d5955cfb1186f2fb4d263cd6a71400c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blocks-smartDistrubution-v2.0.3a-sources.jar",
          "url": "blocks-smartDistrubution-v2.0.3a-sources.jar",
          "size": 7465,
          "sha512": "fbafa3fe6f3082151b074e1546fb5f2887cf744288f3d5d4f54ce0d0033547c2dc57c8c3a326b6dc8e086f513b6abd3d37b189ac8956621a9fb6c726774948cc",
          "sha256": "fdbbb67dbb34ff43f61a095ab0326b82444519e31022df41fef9e2efd9277245",
          "sha1": "6d7d81fe65b72d5f26820c8e5159c1f63d7de276",
          "md5": "cae8711b7f642d00b2df2e429200ce77"
        },
        {
          "name": "blocks-smartDistrubution-v2.0.3a-sources.jar",
          "url": "blocks-smartDistrubution-v2.0.3a-sources.jar",
          "size": 7465,
          "sha512": "fbafa3fe6f3082151b074e1546fb5f2887cf744288f3d5d4f54ce0d0033547c2dc57c8c3a326b6dc8e086f513b6abd3d37b189ac8956621a9fb6c726774948cc",
          "sha256": "fdbbb67dbb34ff43f61a095ab0326b82444519e31022df41fef9e2efd9277245",
          "sha1": "6d7d81fe65b72d5f26820c8e5159c1f63d7de276",
          "md5": "cae8711b7f642d00b2df2e429200ce77"
        }
      ]
    }
  ]
}
