{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.MindustryModCore",
    "module": "blocks-diagonalBridges",
    "version": "repo-test4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.ArcLibrary",
          "module": "graphics-extendedDraw",
          "version": {
            "requires": "v1.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "blocks-diagonalBridges-repo-test4.jar",
          "url": "blocks-diagonalBridges-repo-test4.jar",
          "size": 21409,
          "sha512": "f38376192443ff49712bf7ced939e1938169a50fe16e231705a0985ab4980708079f90ba3c47eb11076146a787d3b4a01617584d2b36d191f96443ad85caf913",
          "sha256": "30560043cce6c6971c8ed7465d8bb748b4762625a4bf31061c8c3da560cecb7f",
          "sha1": "28f8afcc77547d9afd2730814b108c40944d48fc",
          "md5": "fd62b7464a039d1efda4d3b3749bcb62"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.ArcLibrary",
          "module": "graphics-extendedDraw",
          "version": {
            "requires": "v1.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "blocks-diagonalBridges-repo-test4.jar",
          "url": "blocks-diagonalBridges-repo-test4.jar",
          "size": 21409,
          "sha512": "f38376192443ff49712bf7ced939e1938169a50fe16e231705a0985ab4980708079f90ba3c47eb11076146a787d3b4a01617584d2b36d191f96443ad85caf913",
          "sha256": "30560043cce6c6971c8ed7465d8bb748b4762625a4bf31061c8c3da560cecb7f",
          "sha1": "28f8afcc77547d9afd2730814b108c40944d48fc",
          "md5": "fd62b7464a039d1efda4d3b3749bcb62"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blocks-diagonalBridges-repo-test4-sources.jar",
          "url": "blocks-diagonalBridges-repo-test4-sources.jar",
          "size": 6090,
          "sha512": "9f3e854544c81f8c3faba08baf33b81c2966fef4d2baf2c741c514c3f85af775ac980635f40adea853e3551343ec64b41241c16248036e5b4be974198cb10be1",
          "sha256": "bce6589654a393f14d7d666ef2dc9952316cd8e7865c2288cce707e58e510128",
          "sha1": "5ef07f842362d6839fef293e05ec220323e14264",
          "md5": "faf06f4216ae5fef9a2c9763ae5c72e2"
        },
        {
          "name": "blocks-diagonalBridges-repo-test4-sources.jar",
          "url": "blocks-diagonalBridges-repo-test4-sources.jar",
          "size": 6090,
          "sha512": "9f3e854544c81f8c3faba08baf33b81c2966fef4d2baf2c741c514c3f85af775ac980635f40adea853e3551343ec64b41241c16248036e5b4be974198cb10be1",
          "sha256": "bce6589654a393f14d7d666ef2dc9952316cd8e7865c2288cce707e58e510128",
          "sha1": "5ef07f842362d6839fef293e05ec220323e14264",
          "md5": "faf06f4216ae5fef9a2c9763ae5c72e2"
        }
      ]
    }
  ]
}
