{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "dev-annotations",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dev-annotations-unspecified.jar",
          "url": "dev-annotations-unspecified.jar",
          "size": 1448,
          "sha512": "635052b3776f35a999fa6fcc4d0bb5c9e4e36ed2f1789cd91996e3cd51fe80308a74d26d633836b932fbaff6c170cc87c647394a1edf89dcdfe3fb3ce62c7e5e",
          "sha256": "fb033937cdbb9f0c3c54426da41034fcd0ba57733ec16330f42df6e0d205213d",
          "sha1": "1a1c6ebe9a689b076b53f252c70a9baf9c50ee8d",
          "md5": "69b38e6d2f6ab4b6db22cc5f86f3d379"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "dev-annotations-unspecified.jar",
          "url": "dev-annotations-unspecified.jar",
          "size": 1448,
          "sha512": "635052b3776f35a999fa6fcc4d0bb5c9e4e36ed2f1789cd91996e3cd51fe80308a74d26d633836b932fbaff6c170cc87c647394a1edf89dcdfe3fb3ce62c7e5e",
          "sha256": "fb033937cdbb9f0c3c54426da41034fcd0ba57733ec16330f42df6e0d205213d",
          "sha1": "1a1c6ebe9a689b076b53f252c70a9baf9c50ee8d",
          "md5": "69b38e6d2f6ab4b6db22cc5f86f3d379"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dev-annotations-unspecified-sources.jar",
          "url": "dev-annotations-unspecified-sources.jar",
          "size": 1386,
          "sha512": "cb8702df2337e6c60c326f9d89aea48565ae9ea14f6abcc9609e5768ef9d5f972a84a29d8a93a59eb5900127fea90fad7368b99e559f81b74f50dee6a9b5d45c",
          "sha256": "b4a2860b244d229de5a11d8eb7f56e1399db62c18c3ebf83af67a0d83a49c4a7",
          "sha1": "45fcbc6976cbc76c16036ae45b44b4945484bfbf",
          "md5": "746568a290a70efd2420a3b2a961fed9"
        }
      ]
    }
  ]
}
