{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "util-classfile-metadata",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "util-classfile-metadata-unspecified.jar",
          "url": "util-classfile-metadata-unspecified.jar",
          "size": 10640,
          "sha512": "b5b06cf78d818ca815123ebcc9fef0e95fbc7531f13594501e002ccd1214fff924f7bc4bfb8ac15c76b2fc2be3df26ca3877d09d30cafd0255c0530d9ba33019",
          "sha256": "eb7f78463dbc8abc01b40b1ac6c7981d7b574566365b71dfa3c784368e7a79e9",
          "sha1": "d1f1ec47b70c96f2013ac881dd19e4030f5eca23",
          "md5": "bde14d38d90eefe5b86cf65ea61b263e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "util-classfile-metadata-unspecified.jar",
          "url": "util-classfile-metadata-unspecified.jar",
          "size": 10640,
          "sha512": "b5b06cf78d818ca815123ebcc9fef0e95fbc7531f13594501e002ccd1214fff924f7bc4bfb8ac15c76b2fc2be3df26ca3877d09d30cafd0255c0530d9ba33019",
          "sha256": "eb7f78463dbc8abc01b40b1ac6c7981d7b574566365b71dfa3c784368e7a79e9",
          "sha1": "d1f1ec47b70c96f2013ac881dd19e4030f5eca23",
          "md5": "bde14d38d90eefe5b86cf65ea61b263e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "util-classfile-metadata-unspecified-sources.jar",
          "url": "util-classfile-metadata-unspecified-sources.jar",
          "size": 4549,
          "sha512": "072e3fbda9baa153f976e2121aadebccdf9c0959b5cfd3613e6d68d62768cee170eb37fb61d6a42a330083d089689475729eb78c56fc8051fb459c89a5f38e7d",
          "sha256": "50666fad5741e678edfb3d5ca2d5e54828e5444d86f732d31dc53bbd3d8e7d63",
          "sha1": "a4471fa740a423ad06ce00baf97ba010245cf4a0",
          "md5": "04331e1654b0a1405264948ba121d034"
        }
      ]
    }
  ]
}
