{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.MindustryModCore",
    "module": "blocks",
    "version": "repo-test1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.ArcLibrary",
          "module": "graphics-extendedDraw",
          "version": {
            "requires": "v1.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "blocks-repo-test1.jar",
          "url": "blocks-repo-test1.jar",
          "size": 173026,
          "sha512": "fc15ec66b6923e15348a70bdb9a17380c2f8440348669e8373adb982e23fca580b76a395c640ba8b07706bc188494cdf8ca1503dd3ccee91454e63570de4e470",
          "sha256": "10bd844070b96e753a98192219af2574724ce2ebafa92d9248673fe1c87d0627",
          "sha1": "d7f3f4e2865673f8a00fd615047c11cb4cf1a54d",
          "md5": "bce69ec1fe3efcff469e6fb31319706b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.MindustryModCore",
          "module": "core",
          "version": {
            "requires": "repo-test1"
          }
        },
        {
          "group": "com.github.Zelaux.MindustryModCore",
          "module": "graphics",
          "version": {
            "requires": "repo-test1"
          }
        },
        {
          "group": "com.github.Zelaux.ArcLibrary",
          "module": "graphics-extendedDraw",
          "version": {
            "requires": "v1.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "blocks-repo-test1.jar",
          "url": "blocks-repo-test1.jar",
          "size": 173026,
          "sha512": "fc15ec66b6923e15348a70bdb9a17380c2f8440348669e8373adb982e23fca580b76a395c640ba8b07706bc188494cdf8ca1503dd3ccee91454e63570de4e470",
          "sha256": "10bd844070b96e753a98192219af2574724ce2ebafa92d9248673fe1c87d0627",
          "sha1": "d7f3f4e2865673f8a00fd615047c11cb4cf1a54d",
          "md5": "bce69ec1fe3efcff469e6fb31319706b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blocks-repo-test1-sources.jar",
          "url": "blocks-repo-test1-sources.jar",
          "size": 32651,
          "sha512": "5cde1027b307ab522da1d51f262261da495ee923d3422952904a5a61505201a12a97067f34c0e75413285ba1e21b10c0d8f76e75a67a73d21ec5a0b3b7a0bbca",
          "sha256": "bf006a59ef8a0f3245ea48ffe5ea4745d100f7b0ef44f95a78c73d584a5d139a",
          "sha1": "e5a7efaf4fae2fb68c3d1a079df0375a6a6a9d1e",
          "md5": "67086886d9107e6eebf27b181e777177"
        },
        {
          "name": "blocks-repo-test1-sources.jar",
          "url": "blocks-repo-test1-sources.jar",
          "size": 32651,
          "sha512": "5cde1027b307ab522da1d51f262261da495ee923d3422952904a5a61505201a12a97067f34c0e75413285ba1e21b10c0d8f76e75a67a73d21ec5a0b3b7a0bbca",
          "sha256": "bf006a59ef8a0f3245ea48ffe5ea4745d100f7b0ef44f95a78c73d584a5d139a",
          "sha1": "e5a7efaf4fae2fb68c3d1a079df0375a6a6a9d1e",
          "md5": "67086886d9107e6eebf27b181e777177"
        }
      ]
    }
  ]
}
