{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.MindustryModCore",
    "module": "blocks",
    "version": "repo-test1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.ArcLibrary",
          "module": "graphics-extendedDraw",
          "version": {
            "requires": "v1.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "blocks-repo-test1.jar",
          "url": "blocks-repo-test1.jar",
          "size": 173027,
          "sha512": "143d9e69f58bcd4bcfc322f1647fa37bae3fbdaf0b4d55e9a3f0c1173909c037dc5260a930f025f1bd0f0477baf5286179b31266e95c8f30d38e9636bbb7165f",
          "sha256": "9a7faa870a8bb5107ff9dc5f7c92d5f2b0a5504bba31de205788a6d4afcc3219",
          "sha1": "fbfa6a2f6811ffd8a35f8533c82fd11842de42ef",
          "md5": "660afc49ce26ff157e66adadb58f067b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.MindustryModCore",
          "module": "core",
          "version": {
            "requires": "repo-test1"
          }
        },
        {
          "group": "com.github.Zelaux.MindustryModCore",
          "module": "graphics",
          "version": {
            "requires": "repo-test1"
          }
        },
        {
          "group": "com.github.Zelaux.ArcLibrary",
          "module": "graphics-extendedDraw",
          "version": {
            "requires": "v1.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "blocks-repo-test1.jar",
          "url": "blocks-repo-test1.jar",
          "size": 173027,
          "sha512": "143d9e69f58bcd4bcfc322f1647fa37bae3fbdaf0b4d55e9a3f0c1173909c037dc5260a930f025f1bd0f0477baf5286179b31266e95c8f30d38e9636bbb7165f",
          "sha256": "9a7faa870a8bb5107ff9dc5f7c92d5f2b0a5504bba31de205788a6d4afcc3219",
          "sha1": "fbfa6a2f6811ffd8a35f8533c82fd11842de42ef",
          "md5": "660afc49ce26ff157e66adadb58f067b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blocks-repo-test1-sources.jar",
          "url": "blocks-repo-test1-sources.jar",
          "size": 32651,
          "sha512": "9cc6f2ddd677909c62f7e66637a1f61a44ebb3d0ca2abec6327bdd5a6d516cdd46bca24bf8799eb40d256b265dbbba069ba44fc7b14fdef49997165b6e13b0f7",
          "sha256": "f631b0148510dd65dace4d542307a5eafb819a2bbd9c970660da93cd79410b10",
          "sha1": "71f403b17ca80acbb6f226ff7a4689305909abb2",
          "md5": "d0c65b5934fe9d1be6b8b6d10de24623"
        },
        {
          "name": "blocks-repo-test1-sources.jar",
          "url": "blocks-repo-test1-sources.jar",
          "size": 32651,
          "sha512": "9cc6f2ddd677909c62f7e66637a1f61a44ebb3d0ca2abec6327bdd5a6d516cdd46bca24bf8799eb40d256b265dbbba069ba44fc7b14fdef49997165b6e13b0f7",
          "sha256": "f631b0148510dd65dace4d542307a5eafb819a2bbd9c970660da93cd79410b10",
          "sha1": "71f403b17ca80acbb6f226ff7a4689305909abb2",
          "md5": "d0c65b5934fe9d1be6b8b6d10de24623"
        }
      ]
    }
  ]
}
