{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "ui",
    "version": "v1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-v1.0.6.jar",
          "url": "ui-v1.0.6.jar",
          "size": 261,
          "sha512": "7d462993b78e5fbd97e6d59722cda01fdde56c3b7b8dcc1859c6416686d544966b8fc97cb240f7e37d5d09f84d68c55fb699bdb5f0b9ac85af12def7ef03cb06",
          "sha256": "8923ed3602421ef2673b100ee59de9c8f64b4fa051c7a80ceb0e850fb59a1ab4",
          "sha1": "fe83a02068a3bf8401d34e1b21a7b7b07c2e4d28",
          "md5": "e146e7645f250e92bcd1657e0c4eba5f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-v1.0.6.jar",
          "url": "ui-v1.0.6.jar",
          "size": 261,
          "sha512": "7d462993b78e5fbd97e6d59722cda01fdde56c3b7b8dcc1859c6416686d544966b8fc97cb240f7e37d5d09f84d68c55fb699bdb5f0b9ac85af12def7ef03cb06",
          "sha256": "8923ed3602421ef2673b100ee59de9c8f64b4fa051c7a80ceb0e850fb59a1ab4",
          "sha1": "fe83a02068a3bf8401d34e1b21a7b7b07c2e4d28",
          "md5": "e146e7645f250e92bcd1657e0c4eba5f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-v1.0.6-sources.jar",
          "url": "ui-v1.0.6-sources.jar",
          "size": 261,
          "sha512": "7d462993b78e5fbd97e6d59722cda01fdde56c3b7b8dcc1859c6416686d544966b8fc97cb240f7e37d5d09f84d68c55fb699bdb5f0b9ac85af12def7ef03cb06",
          "sha256": "8923ed3602421ef2673b100ee59de9c8f64b4fa051c7a80ceb0e850fb59a1ab4",
          "sha1": "fe83a02068a3bf8401d34e1b21a7b7b07c2e4d28",
          "md5": "e146e7645f250e92bcd1657e0c4eba5f"
        }
      ]
    }
  ]
}
