{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.MindustryModCore",
    "module": "plugins",
    "version": "repo-test7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugins-repo-test7.jar",
          "url": "plugins-repo-test7.jar",
          "size": 3214,
          "sha512": "2c8843df786b92e2346d138a51eb73dd22c751075b9feb7e542ba31dc96338bcf4ea2f1ff5503cfffa54c2f532a1188ab53c0712afc467b04a36ed10e4e5dca9",
          "sha256": "7d6afa96dd5c7e4010fe3c9d7c1475675b0783dc2b7652f406112ff357fbf4ec",
          "sha1": "c58a5f1bc4d0bf8bb51ec9173fc7b5ab0605894c",
          "md5": "6ceb3979e479f86da2d5f0f2f4eefd53"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugins-repo-test7.jar",
          "url": "plugins-repo-test7.jar",
          "size": 3214,
          "sha512": "2c8843df786b92e2346d138a51eb73dd22c751075b9feb7e542ba31dc96338bcf4ea2f1ff5503cfffa54c2f532a1188ab53c0712afc467b04a36ed10e4e5dca9",
          "sha256": "7d6afa96dd5c7e4010fe3c9d7c1475675b0783dc2b7652f406112ff357fbf4ec",
          "sha1": "c58a5f1bc4d0bf8bb51ec9173fc7b5ab0605894c",
          "md5": "6ceb3979e479f86da2d5f0f2f4eefd53"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugins-repo-test7-sources.jar",
          "url": "plugins-repo-test7-sources.jar",
          "size": 1546,
          "sha512": "18306687cdf4e806a20dcbc3d544aa6086e77826ca1d4243fc0151b32ca23f2e3a7e6fa363c1736e63e7172836ae59bf5fadd8c42d8e4a2596aebaeb3cfe3cd9",
          "sha256": "256711753d88902edd08f2b4fb301ca00a4dd908c0865ca692714eacbca4c7ed",
          "sha1": "6dcc162e8068eeaafa77484a6fe51e60c24cf102",
          "md5": "46a9561bb95648705ded706f1aa2b78e"
        }
      ]
    }
  ]
}
