{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "util-visitor",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "util-visitor-unspecified.jar",
          "url": "util-visitor-unspecified.jar",
          "size": 18024,
          "sha512": "e9a1d92975a35c447b033f9030aa17a59b637223ba1704bf0662c78414aa55d3b2efee950d37bd2abc59086ea0a7dceb6f20952cd95147c459c8d03354169c29",
          "sha256": "47e0947dd294f54dacb76248609b95ad61a34a758d2f575e5ca1bee6e421ea37",
          "sha1": "b6c303a940351f2a05609998d2ce7999e07e5e99",
          "md5": "e05c7fc123c67bdd4c996e758f149760"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "util-visitor-unspecified.jar",
          "url": "util-visitor-unspecified.jar",
          "size": 18024,
          "sha512": "e9a1d92975a35c447b033f9030aa17a59b637223ba1704bf0662c78414aa55d3b2efee950d37bd2abc59086ea0a7dceb6f20952cd95147c459c8d03354169c29",
          "sha256": "47e0947dd294f54dacb76248609b95ad61a34a758d2f575e5ca1bee6e421ea37",
          "sha1": "b6c303a940351f2a05609998d2ce7999e07e5e99",
          "md5": "e05c7fc123c67bdd4c996e758f149760"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "util-visitor-unspecified-sources.jar",
          "url": "util-visitor-unspecified-sources.jar",
          "size": 7968,
          "sha512": "ed9e93805bfa1a592528ba5c5b2aab124b0714690f0fb3ef225cc518278f6bc4a03b864e5634f17949c7cd0c64ead8ff977003d03a61d74da61bf97e0a4795b1",
          "sha256": "9e200691e1c5348698f6ec80e28a6e5e1534860ad6522ffcd6eacb68c64a2dfc",
          "sha1": "19ddb19d67fd8e5eb90fc55f48b5b29eb0835bf1",
          "md5": "48a689ee2dfb9e48d58394faa8b0d98d"
        }
      ]
    }
  ]
}
