{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "graphics-dashDraw",
    "version": "v1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphics-dashDraw-v1.0.5.jar",
          "url": "graphics-dashDraw-v1.0.5.jar",
          "size": 5361,
          "sha512": "89eb36c3fa6349f055fa1a78441353272d985bb5ee70efe8085912313c45a8012ad9a7cba6b8b2069214edecb0ada9eb6315fe21409fbc809af5092443ee64a1",
          "sha256": "a55d863f38ecf825a81946c6ed116bf1fd51fdfe08c97196d9ef52bdd56691a2",
          "sha1": "c3ad1b38a6977bb8ac0af5966f783ff0ba17b3eb",
          "md5": "a874fb29b40bf22fb88af62681fb9383"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphics-dashDraw-v1.0.5.jar",
          "url": "graphics-dashDraw-v1.0.5.jar",
          "size": 5361,
          "sha512": "89eb36c3fa6349f055fa1a78441353272d985bb5ee70efe8085912313c45a8012ad9a7cba6b8b2069214edecb0ada9eb6315fe21409fbc809af5092443ee64a1",
          "sha256": "a55d863f38ecf825a81946c6ed116bf1fd51fdfe08c97196d9ef52bdd56691a2",
          "sha1": "c3ad1b38a6977bb8ac0af5966f783ff0ba17b3eb",
          "md5": "a874fb29b40bf22fb88af62681fb9383"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphics-dashDraw-v1.0.5-sources.jar",
          "url": "graphics-dashDraw-v1.0.5-sources.jar",
          "size": 2735,
          "sha512": "80144806d7f13623b05e021754449226aeb627f92d9bc9079017aeeb5f28ac65bb58ea864d2d27a3f8f022433fd7e1e0a5b4d81c0f18ad14ca8be909c8025ba2",
          "sha256": "2d134dd0263e813c20f975c4292f3427c1c607ce10bf734441a4d3a719b35b23",
          "sha1": "3efd3e296a9fca5f919bede4e6ce508e72d52001",
          "md5": "0c137244e56e07a97e13eef33d7da537"
        }
      ]
    }
  ]
}
