{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "graphics-dashDraw",
    "version": "v1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphics-dashDraw-v1.0.5.jar",
          "url": "graphics-dashDraw-v1.0.5.jar",
          "size": 5361,
          "sha512": "3b9eea239a319806872c9c6e7b65d60a58cb9c2f6563570360d38274474ccbeb130427ac171c343e0fccdec4442b1931509a82db827b48aed416b529c0b62f1f",
          "sha256": "3c12b7e0342a3d2dd6066bc5f9ab4a8c44faf19ea9ab4051142b60cfae90873a",
          "sha1": "5336c09ce17a1ac0b77913f7bcf28653db6f1523",
          "md5": "1efc33139c9d813b1b652ad485509238"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphics-dashDraw-v1.0.5.jar",
          "url": "graphics-dashDraw-v1.0.5.jar",
          "size": 5361,
          "sha512": "3b9eea239a319806872c9c6e7b65d60a58cb9c2f6563570360d38274474ccbeb130427ac171c343e0fccdec4442b1931509a82db827b48aed416b529c0b62f1f",
          "sha256": "3c12b7e0342a3d2dd6066bc5f9ab4a8c44faf19ea9ab4051142b60cfae90873a",
          "sha1": "5336c09ce17a1ac0b77913f7bcf28653db6f1523",
          "md5": "1efc33139c9d813b1b652ad485509238"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphics-dashDraw-v1.0.5-sources.jar",
          "url": "graphics-dashDraw-v1.0.5-sources.jar",
          "size": 2735,
          "sha512": "b32d020cc63409736bc95ceac41d81c39662f308b460f17b0b4028135b206a953e82cb7213a3325dc16663ca3ab6c0b09a4336ce971490dcf2263aa858f2802f",
          "sha256": "9e15b15a395feb6cc508bcf50ffcb111770aab9d04e2c05b3179fdd523d4b8c3",
          "sha1": "2b737823c3fd8e5925d7f8f0c9ba04a644c3fd5f",
          "md5": "dbfc5e70779cefeafb83a3fc28d8c09a"
        }
      ]
    }
  ]
}
