{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.MindustryModCore",
    "module": "tools",
    "version": "repo-test1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tools-repo-test1.jar",
          "url": "tools-repo-test1.jar",
          "size": 28475009,
          "sha512": "b46517ea41576ddf9df114794b7e844784768e8ab987a0699217be0422d2a53bd5460cc51175fa15702bce610d09a2a84e88d8733798df7668c0643ae70fc0d6",
          "sha256": "60f81bda97be4c0b35fbc5f41f0d08e0cfe003fad7b8061dde227671a6e86a6f",
          "sha1": "8a46fc44bb5d5a377882ea32c1750586c9371523",
          "md5": "568ad7412a2389f0200ada384c75050d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-svgrasterizer",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "com.github.Zelaux.MindustryModCore",
          "module": "core",
          "version": {
            "requires": "repo-test1"
          }
        },
        {
          "group": "com.github.Zelaux.MindustryModCore",
          "module": "annotations",
          "version": {
            "requires": "repo-test1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v146"
          }
        },
        {
          "group": "com.github.javaparser",
          "module": "javaparser-symbol-solver-core",
          "version": {
            "requires": "3.22.1"
          }
        },
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "3.5.0.201409260305-r"
          }
        }
      ],
      "files": [
        {
          "name": "tools-repo-test1.jar",
          "url": "tools-repo-test1.jar",
          "size": 28475009,
          "sha512": "b46517ea41576ddf9df114794b7e844784768e8ab987a0699217be0422d2a53bd5460cc51175fa15702bce610d09a2a84e88d8733798df7668c0643ae70fc0d6",
          "sha256": "60f81bda97be4c0b35fbc5f41f0d08e0cfe003fad7b8061dde227671a6e86a6f",
          "sha1": "8a46fc44bb5d5a377882ea32c1750586c9371523",
          "md5": "568ad7412a2389f0200ada384c75050d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tools-repo-test1-sources.jar",
          "url": "tools-repo-test1-sources.jar",
          "size": 40230,
          "sha512": "701ed775830db4de5b18fac83f3f50093a324be5b217e24ab7ede4e65f77464f86566a76bd3cf14b69312c8c43b6f39cd53598e3fb82d8efe6490e294d35ec37",
          "sha256": "133a4a98458e420f9531ca7be5414a4aa6ac6b2b55365f648333cbbfd354dbd3",
          "sha1": "26158997f9ed9fdf2fdc672ad5e480ae12c86136",
          "md5": "d6ed4e66a385072e0a192c865cb7aa5b"
        }
      ]
    }
  ]
}
