{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "ui",
    "version": "v1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-v1.0.5.jar",
          "url": "ui-v1.0.5.jar",
          "size": 261,
          "sha512": "d6d920388aa5990faef529b5b041be378b78709f6d1d404ed29414fd372f4af4876c6b04e5b09fcbe5b65ec2fbf476b3cf39f659fbf7a58644451f325b1f9aee",
          "sha256": "57705c2032169beb4de1dc5330e915624cc24c403f81b37f648d3eead9b12359",
          "sha1": "ca825ccbb41bc059a7f751601e091a8713776481",
          "md5": "c0bb673231f8ee7f2eda1058dee376d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-v1.0.5.jar",
          "url": "ui-v1.0.5.jar",
          "size": 261,
          "sha512": "d6d920388aa5990faef529b5b041be378b78709f6d1d404ed29414fd372f4af4876c6b04e5b09fcbe5b65ec2fbf476b3cf39f659fbf7a58644451f325b1f9aee",
          "sha256": "57705c2032169beb4de1dc5330e915624cc24c403f81b37f648d3eead9b12359",
          "sha1": "ca825ccbb41bc059a7f751601e091a8713776481",
          "md5": "c0bb673231f8ee7f2eda1058dee376d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-v1.0.5-sources.jar",
          "url": "ui-v1.0.5-sources.jar",
          "size": 261,
          "sha512": "d6d920388aa5990faef529b5b041be378b78709f6d1d404ed29414fd372f4af4876c6b04e5b09fcbe5b65ec2fbf476b3cf39f659fbf7a58644451f325b1f9aee",
          "sha256": "57705c2032169beb4de1dc5330e915624cc24c403f81b37f648d3eead9b12359",
          "sha1": "ca825ccbb41bc059a7f751601e091a8713776481",
          "md5": "c0bb673231f8ee7f2eda1058dee376d1"
        }
      ]
    }
  ]
}
