{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "annotations-packable-class",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "annotations-packable-class-unspecified.jar",
          "url": "annotations-packable-class-unspecified.jar",
          "size": 15226,
          "sha512": "6a8bbf0484056d7502ab2dfd9613be27e4b16863ab56d9d03a4261c4cfeb06d249d0fca7121750b1d0d473f636e8388a7ecd5d8c573fc2e81aeed06db9765e79",
          "sha256": "915eff0997d342847f6872c6c2f69c39e02e8b40957b495fa5e7c5ddf3234eea",
          "sha1": "1b6c1442661a9d5e8ecb8b359e85c9f969c408a3",
          "md5": "f443a19e2b2e96abcae204b864ea061c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "annotations-lombok-plugin-starter",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "com.github.javaparser",
          "module": "javaparser-symbol-solver-core",
          "version": {
            "requires": "3.26.0"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-packable-class-unspecified.jar",
          "url": "annotations-packable-class-unspecified.jar",
          "size": 15226,
          "sha512": "6a8bbf0484056d7502ab2dfd9613be27e4b16863ab56d9d03a4261c4cfeb06d249d0fca7121750b1d0d473f636e8388a7ecd5d8c573fc2e81aeed06db9765e79",
          "sha256": "915eff0997d342847f6872c6c2f69c39e02e8b40957b495fa5e7c5ddf3234eea",
          "sha1": "1b6c1442661a9d5e8ecb8b359e85c9f969c408a3",
          "md5": "f443a19e2b2e96abcae204b864ea061c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-packable-class-unspecified-sources.jar",
          "url": "annotations-packable-class-unspecified-sources.jar",
          "size": 6593,
          "sha512": "17f7d164bd76c564ab534b5377e32ca16ce89176faba0fb4ecf026e5a59a0d4b84a4a47d38ca6bbc6f546948e678b790377a6de027ae2838a73b1d0637e618dd",
          "sha256": "bb099474df88b93a33d989c236bc6073ca13f6fb1101615121c854e5e52016f2",
          "sha1": "9f47e43932981320f9886932fb129f7dfe88c336",
          "md5": "2d486ab8402a79b252ddb0889d205373"
        }
      ]
    }
  ]
}
