{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "annotations-debug-print",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "annotations-lombok-plugin-starter",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-debug-print-unspecified.jar",
          "url": "annotations-debug-print-unspecified.jar",
          "size": 12520,
          "sha512": "dca101e6202bcf994ed29a659935aeb0ec65913fecca9e60e22ce077d5e347fae6cebaaf6dc668496c85e636cdf047ef18748780794244fddb508c937a919771",
          "sha256": "d516aedefb7b52fee070c22a3810ec1b1f95d1a3289af096813b7242f85d1047",
          "sha1": "8651c9142852952445adbafeb7635a3acf2e1066",
          "md5": "e98f13a7a37b0538f8d18679e760ea04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "util-classfile-metadata",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "util-node",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "annotations-lombok-plugin-starter",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-debug-print-unspecified.jar",
          "url": "annotations-debug-print-unspecified.jar",
          "size": 12520,
          "sha512": "dca101e6202bcf994ed29a659935aeb0ec65913fecca9e60e22ce077d5e347fae6cebaaf6dc668496c85e636cdf047ef18748780794244fddb508c937a919771",
          "sha256": "d516aedefb7b52fee070c22a3810ec1b1f95d1a3289af096813b7242f85d1047",
          "sha1": "8651c9142852952445adbafeb7635a3acf2e1066",
          "md5": "e98f13a7a37b0538f8d18679e760ea04"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-debug-print-unspecified-sources.jar",
          "url": "annotations-debug-print-unspecified-sources.jar",
          "size": 5562,
          "sha512": "271dc12028d71b56784944b3e4fd3309f772b1e4c2831c1d8b97040d3ed70cf55dfd03933dee643a1889f52ea7a15406f4bfc7e93fc110f77e1e42a0e25c1794",
          "sha256": "e3459e8d6db3b750cec75a276d0dae9be2b469e0bea1e2d6e944f065f0694c58",
          "sha1": "ca2e2f56a2c8e8e54f4438a29810a3a5ded4721a",
          "md5": "32bbda80582b25ca277d835510a9d4b2"
        }
      ]
    }
  ]
}
