{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "analytics-object-creation",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "analytics-object-creation-unspecified.jar",
          "url": "analytics-object-creation-unspecified.jar",
          "size": 4836,
          "sha512": "2efd4da1d5bda56714a209ad818e4bb7c14a31884f8caad6d5ea0c5174fb4bdba0ba293e62c42ef164c55bd03b545e7be2c3431254a511f4d59ec4db24d9a291",
          "sha256": "452948404a7fd6e47a5870f8627bdf58115ac1dd54bd46c11b034ef5e587a783",
          "sha1": "e7e8ffb0fedaadfb63c6ecf9566f48520614dad9",
          "md5": "dc8d6ec30b2d76e11347485172f1084c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "analytics-object-creation-unspecified.jar",
          "url": "analytics-object-creation-unspecified.jar",
          "size": 4836,
          "sha512": "2efd4da1d5bda56714a209ad818e4bb7c14a31884f8caad6d5ea0c5174fb4bdba0ba293e62c42ef164c55bd03b545e7be2c3431254a511f4d59ec4db24d9a291",
          "sha256": "452948404a7fd6e47a5870f8627bdf58115ac1dd54bd46c11b034ef5e587a783",
          "sha1": "e7e8ffb0fedaadfb63c6ecf9566f48520614dad9",
          "md5": "dc8d6ec30b2d76e11347485172f1084c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "analytics-object-creation-unspecified-sources.jar",
          "url": "analytics-object-creation-unspecified-sources.jar",
          "size": 2878,
          "sha512": "26763d3a0c6a20032431d71c10e6099c703cc8f1c9052ffbcffe2ab1cc82ce4b7cb90a4f8f675ea6e007984dbcbd09535fee053bd472a54c3adfb4aa2129f641",
          "sha256": "f71bc3aef7fa251d16293fae2cdb43e5b57010d88898e42a756606db2fc12863",
          "sha1": "280a77358c82c6fe39be07beefc24b534247cfe8",
          "md5": "3101d2b1b2bccd5248ba2bbb2995dade"
        }
      ]
    }
  ]
}
