{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "graphics-draw3d",
    "version": "v1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphics-draw3d-v1.0.5.jar",
          "url": "graphics-draw3d-v1.0.5.jar",
          "size": 2718,
          "sha512": "ec666df3683b05ad26f96adc6ea6b61466c2328fb7abaa584a8412ae738301abced5d5d261086acddf18f4677044d17d2a375ab550bf23635ba0a3e8caa94059",
          "sha256": "57a3103d2e10a346fcdf5f00743b80776fc229a658699ae56b92463493a9e3b4",
          "sha1": "8b0be810d7e88ca1b546de084e4898198103773b",
          "md5": "2b0bf74137dcfb54ee9e18bc31cc7345"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphics-draw3d-v1.0.5.jar",
          "url": "graphics-draw3d-v1.0.5.jar",
          "size": 2718,
          "sha512": "ec666df3683b05ad26f96adc6ea6b61466c2328fb7abaa584a8412ae738301abced5d5d261086acddf18f4677044d17d2a375ab550bf23635ba0a3e8caa94059",
          "sha256": "57a3103d2e10a346fcdf5f00743b80776fc229a658699ae56b92463493a9e3b4",
          "sha1": "8b0be810d7e88ca1b546de084e4898198103773b",
          "md5": "2b0bf74137dcfb54ee9e18bc31cc7345"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphics-draw3d-v1.0.5-sources.jar",
          "url": "graphics-draw3d-v1.0.5-sources.jar",
          "size": 1638,
          "sha512": "d244e7db0fc7dc8384feeac744cd6256ba9735a6a1f2d49a7f261305e001820059ada5c6bc43cdc41e2fefe276c243410760ae71ec1583e979352ff679c8a879",
          "sha256": "17ece698aa1761786cd59b7c499f96d0c16089a3ff300336af6ee07111a93432",
          "sha1": "2fbc3c66fd89dcc36c432acd8f830dcf0c37cf9f",
          "md5": "fa77666c1ec9d947aecd48564ded5ffe"
        }
      ]
    }
  ]
}
