{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "utils-files",
    "version": "v1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "utils-files-v1.0.5.jar",
          "url": "utils-files-v1.0.5.jar",
          "size": 2047,
          "sha512": "790ec16681dbac20559e8cc2136a80630f52a623f117dc321eb33dce5b8569fa552391e8341074f0555acb32e2c1c1f2518b821d42d39834004b05bd147c9296",
          "sha256": "1382b3595859a5316c869f6017c7a171a79ef827c52601b7705b361db77cf979",
          "sha1": "454dd187da8a581818fb9afa288234f3fb16a5df",
          "md5": "774b56c1eae1dc24548dc884032975da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-files-v1.0.5.jar",
          "url": "utils-files-v1.0.5.jar",
          "size": 2047,
          "sha512": "790ec16681dbac20559e8cc2136a80630f52a623f117dc321eb33dce5b8569fa552391e8341074f0555acb32e2c1c1f2518b821d42d39834004b05bd147c9296",
          "sha256": "1382b3595859a5316c869f6017c7a171a79ef827c52601b7705b361db77cf979",
          "sha1": "454dd187da8a581818fb9afa288234f3fb16a5df",
          "md5": "774b56c1eae1dc24548dc884032975da"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-files-v1.0.5-sources.jar",
          "url": "utils-files-v1.0.5-sources.jar",
          "size": 1456,
          "sha512": "101940b342af119ab97beef02e97de3caa6030069183c8c7e13055f75947d6febfcd5344bd410b56e1c76702486893e5cc03b125823ade11f7c8d7db69d58522",
          "sha256": "6796357f813ae1522fb98445b2efe289c45e72c327f19d2519745d71b254f09f",
          "sha1": "a881b2278a585a833f525eeae914f8c7d8407414",
          "md5": "78181a20998a53655a51def2e4604631"
        }
      ]
    }
  ]
}
