{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "dev-annotations",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dev-annotations-1.0.jar",
          "url": "dev-annotations-1.0.jar",
          "size": 1448,
          "sha512": "891437701cee3d3478f5eef26b5f5d79e06ee6d3b6028b533683c2c9ee207ca070a4f04fb4ef0f24a267d7c098093576f892976cf73d710b4974dd0b58b53958",
          "sha256": "2be86287932d2486e05b392991a5784e3f2e10dd974745ef18262ec345d202ab",
          "sha1": "b7753c0812311b5ba52957f04dda9effd1fceda3",
          "md5": "b31ed8a93b394290d9c6291b306b8ae3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "dev-annotations-1.0.jar",
          "url": "dev-annotations-1.0.jar",
          "size": 1448,
          "sha512": "891437701cee3d3478f5eef26b5f5d79e06ee6d3b6028b533683c2c9ee207ca070a4f04fb4ef0f24a267d7c098093576f892976cf73d710b4974dd0b58b53958",
          "sha256": "2be86287932d2486e05b392991a5784e3f2e10dd974745ef18262ec345d202ab",
          "sha1": "b7753c0812311b5ba52957f04dda9effd1fceda3",
          "md5": "b31ed8a93b394290d9c6291b306b8ae3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dev-annotations-1.0-sources.jar",
          "url": "dev-annotations-1.0-sources.jar",
          "size": 1386,
          "sha512": "6fa83c5eb30181faf31bbaa834106e9a962bc3e3cdeaf2906b618d7747573c789594abf774f31d7d09d9574b8c56bba2420f21ad8f2ec7b67df4d6a6ede7cffa",
          "sha256": "f61e45c18149fbed8c86de05ac41bd723f5485c290eeb46bb58dba6992057141",
          "sha1": "fa53037c186498c873b5419cdc75b499a4598ffd",
          "md5": "b6068712136585c46d113069dd8f7580"
        }
      ]
    }
  ]
}
