{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "graphics-extendedDraw",
    "version": "v1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphics-extendedDraw-v1.0.5.jar",
          "url": "graphics-extendedDraw-v1.0.5.jar",
          "size": 7080,
          "sha512": "d088391f21a96c65a6a28acfb9173d0f9d03ff89f00e725dc254a3968fcfa2dc01eee7a0f08443b2fb38d8b4a0f2c9dcd6ccb805fa3a6f5ba95816e0740c1227",
          "sha256": "5732e90d7460b0fd0f5977d45a7686ef21281ac10be47a918b7be555ceebcc49",
          "sha1": "971fd92abbba286acd61ce9fac43448b4b431c3d",
          "md5": "96910f5b5c805d36258e68f8a6e2dc1d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphics-extendedDraw-v1.0.5.jar",
          "url": "graphics-extendedDraw-v1.0.5.jar",
          "size": 7080,
          "sha512": "d088391f21a96c65a6a28acfb9173d0f9d03ff89f00e725dc254a3968fcfa2dc01eee7a0f08443b2fb38d8b4a0f2c9dcd6ccb805fa3a6f5ba95816e0740c1227",
          "sha256": "5732e90d7460b0fd0f5977d45a7686ef21281ac10be47a918b7be555ceebcc49",
          "sha1": "971fd92abbba286acd61ce9fac43448b4b431c3d",
          "md5": "96910f5b5c805d36258e68f8a6e2dc1d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphics-extendedDraw-v1.0.5-sources.jar",
          "url": "graphics-extendedDraw-v1.0.5-sources.jar",
          "size": 3322,
          "sha512": "72149ead093c0bd4aeecea6d926d46df223bf5dd98ae922faf98b7f189b80813cf00e99f27b63427c2c95cc8dc8411b74a2de5f8aad31b1113081716a2b348c1",
          "sha256": "28076a789f194cbe6caeae72f00f9e17ad73564f52c6f0906a9140e5a41a2e37",
          "sha1": "4cab59531b42cb350a65e3d7a687c3cd2f28a10e",
          "md5": "66f66a7bbd9426a6309e92555fcaa721"
        }
      ]
    }
  ]
}
