{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "annotations-test",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "annotations-test-unspecified.jar",
          "url": "annotations-test-unspecified.jar",
          "size": 8856,
          "sha512": "8e5e50bf4016b9811732dce15fcab109bd52bd091523b956888c5953d69ab5f04633fae617c6321a2c3e5ec2bf200bcf94bde16644cf32651fabb21c47ce56f1",
          "sha256": "1cada64cf858920e673577d72c12b51e86f4222131f23c423a341e85ccc4f425",
          "sha1": "a2e31a220ac84c14d454a97a712d90acd1ae2e95",
          "md5": "6b8b98e64f63498a40e0fa807459e40e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "annotations-debug-print",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "annotations-method-bytecode",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-test-unspecified.jar",
          "url": "annotations-test-unspecified.jar",
          "size": 8856,
          "sha512": "8e5e50bf4016b9811732dce15fcab109bd52bd091523b956888c5953d69ab5f04633fae617c6321a2c3e5ec2bf200bcf94bde16644cf32651fabb21c47ce56f1",
          "sha256": "1cada64cf858920e673577d72c12b51e86f4222131f23c423a341e85ccc4f425",
          "sha1": "a2e31a220ac84c14d454a97a712d90acd1ae2e95",
          "md5": "6b8b98e64f63498a40e0fa807459e40e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-test-unspecified-sources.jar",
          "url": "annotations-test-unspecified-sources.jar",
          "size": 3414,
          "sha512": "0cf4789543d437aa70a30223dbc9d06711d9f92b4c2cc65e13263ffd635dcab9d1272ed43e7067bfd86f7aeb46516a27940be5511721b61e8c0c6e62233e93a5",
          "sha256": "9d133b908d0ffacf4378c0629b838ee8ef1e0ac715377e6cf36b472d8032a821",
          "sha1": "7da607ea449b3d1e8be0eb41a88503db13043ed7",
          "md5": "e2e18891d55bf446820cee406e3b53e6"
        }
      ]
    }
  ]
}
