{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "graphics",
    "version": "v1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphics-v1.0.5.jar",
          "url": "graphics-v1.0.5.jar",
          "size": 261,
          "sha512": "73793ced103eacfa76e70bb1d2952eacb2d29ce8d65fb79615ccc8ae192df5451c7034f99b2ed71bc5203af0fe3350d49f3a910a1a64298508ec948d0f6b4b80",
          "sha256": "ef630db0448cf94dd859ea5e11f1f024b42d2f0bda2ed06d11ca3428e403badd",
          "sha1": "96668b69da927f679a70d1140c13ed02d6813cea",
          "md5": "0de3e66b33e62de4ef4a1a5913a2b803"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphics-v1.0.5.jar",
          "url": "graphics-v1.0.5.jar",
          "size": 261,
          "sha512": "73793ced103eacfa76e70bb1d2952eacb2d29ce8d65fb79615ccc8ae192df5451c7034f99b2ed71bc5203af0fe3350d49f3a910a1a64298508ec948d0f6b4b80",
          "sha256": "ef630db0448cf94dd859ea5e11f1f024b42d2f0bda2ed06d11ca3428e403badd",
          "sha1": "96668b69da927f679a70d1140c13ed02d6813cea",
          "md5": "0de3e66b33e62de4ef4a1a5913a2b803"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphics-v1.0.5-sources.jar",
          "url": "graphics-v1.0.5-sources.jar",
          "size": 261,
          "sha512": "73793ced103eacfa76e70bb1d2952eacb2d29ce8d65fb79615ccc8ae192df5451c7034f99b2ed71bc5203af0fe3350d49f3a910a1a64298508ec948d0f6b4b80",
          "sha256": "ef630db0448cf94dd859ea5e11f1f024b42d2f0bda2ed06d11ca3428e403badd",
          "sha1": "96668b69da927f679a70d1140c13ed02d6813cea",
          "md5": "0de3e66b33e62de4ef4a1a5913a2b803"
        }
      ]
    }
  ]
}
