{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "analytics-object-creation",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "analytics-object-creation-1.0.jar",
          "url": "analytics-object-creation-1.0.jar",
          "size": 4836,
          "sha512": "e770d387d55f0638e1f8018b3b8b7aa3dbbd287e5cf9d86df5a5cce11cae1718c2539894fbf601474460adccf54f260748583271a34af74406e05d92d4a3bc93",
          "sha256": "2930233c67f18be1a8ce4f13254794b9620d458ebdbffa84f243dc65ba3ee9a6",
          "sha1": "0d2ae0c15ad817665ca68d47e9e6299a335e29fe",
          "md5": "60a803fb62f9361a83de312668409384"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "analytics-object-creation-1.0.jar",
          "url": "analytics-object-creation-1.0.jar",
          "size": 4836,
          "sha512": "e770d387d55f0638e1f8018b3b8b7aa3dbbd287e5cf9d86df5a5cce11cae1718c2539894fbf601474460adccf54f260748583271a34af74406e05d92d4a3bc93",
          "sha256": "2930233c67f18be1a8ce4f13254794b9620d458ebdbffa84f243dc65ba3ee9a6",
          "sha1": "0d2ae0c15ad817665ca68d47e9e6299a335e29fe",
          "md5": "60a803fb62f9361a83de312668409384"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "analytics-object-creation-1.0-sources.jar",
          "url": "analytics-object-creation-1.0-sources.jar",
          "size": 2878,
          "sha512": "3acc5be10595ae36b9efc8f2235f89071b8361c50b5a23f470d5d6a19169a43010ad75fd95a1b3658d7e28474bca7bb47fc14dd4fbcc919e1e2eaf65b391533c",
          "sha256": "84b2c71e231385338493b1f37b5ac7923be4b3ee4eacf0adc646b76b954f9676",
          "sha1": "7b87bf0cb3d044eb8b324eea74d9941b445a16de",
          "md5": "f29ade1d52abebfd4e98264a9a955445"
        }
      ]
    }
  ]
}
