{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "transformation-core",
    "version": "v0.9.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "transformation-core-v0.9.4.jar",
          "url": "transformation-core-v0.9.4.jar",
          "size": 14678,
          "sha512": "0f4eea546daf336e8a8a328a5dac4b367eb180b659997bfedd98c4e76f9444b26d840a46b618fd020a8f627296a0536bf78d8dd92ceaa3080132c70d26d08f9d",
          "sha256": "cbaa8621d8511ea21443c034a043006adc92b3c255b9cd36ef4a7690f3d1bfb3",
          "sha1": "ce22481acec72e758047cdc1cafdea81194d8715",
          "md5": "f6e50ce631e55657161e85380a6a6f18"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "transformation-core-v0.9.4.jar",
          "url": "transformation-core-v0.9.4.jar",
          "size": 14678,
          "sha512": "0f4eea546daf336e8a8a328a5dac4b367eb180b659997bfedd98c4e76f9444b26d840a46b618fd020a8f627296a0536bf78d8dd92ceaa3080132c70d26d08f9d",
          "sha256": "cbaa8621d8511ea21443c034a043006adc92b3c255b9cd36ef4a7690f3d1bfb3",
          "sha1": "ce22481acec72e758047cdc1cafdea81194d8715",
          "md5": "f6e50ce631e55657161e85380a6a6f18"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "transformation-core-v0.9.4-sources.jar",
          "url": "transformation-core-v0.9.4-sources.jar",
          "size": 6197,
          "sha512": "51d3c264d7c8c7e9cd92e2e164b793e2585463502de24ba9602224bcb061341e3dcb628897925431aa10335f6b6ff183825ea1da46edb2cdd6f51825bd113b67",
          "sha256": "8ac31539fc70e024a5d6d88b33d46bd2e820575d0e2eafcd009140bf8e39d206",
          "sha1": "79654788c7230c7604be96d71ac7cadacf492f99",
          "md5": "670b75313c0eb5bd4fbcd3c20a7b37d8"
        }
      ]
    }
  ]
}
