{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "graphics-drawText",
    "version": "v1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphics-drawText-v1.0.5.jar",
          "url": "graphics-drawText-v1.0.5.jar",
          "size": 2753,
          "sha512": "c0b50177db842fe7704c2012ff942a893b2390000b023146f4588198088f4b46e508e6f8d93de81d4d322e1ede867a36d0be70887bfe45971d739890b7cf1bd5",
          "sha256": "b1a84c6fcec5d096ec8c65b6e6ddba0d54ac1d274d3d3004116bf720e2b0ef2b",
          "sha1": "eaa1379565cbc361caac1bbd3e24bbb1f0ae1a40",
          "md5": "6d95ae6e85e3175f63aadf13f3a26847"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphics-drawText-v1.0.5.jar",
          "url": "graphics-drawText-v1.0.5.jar",
          "size": 2753,
          "sha512": "c0b50177db842fe7704c2012ff942a893b2390000b023146f4588198088f4b46e508e6f8d93de81d4d322e1ede867a36d0be70887bfe45971d739890b7cf1bd5",
          "sha256": "b1a84c6fcec5d096ec8c65b6e6ddba0d54ac1d274d3d3004116bf720e2b0ef2b",
          "sha1": "eaa1379565cbc361caac1bbd3e24bbb1f0ae1a40",
          "md5": "6d95ae6e85e3175f63aadf13f3a26847"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphics-drawText-v1.0.5-sources.jar",
          "url": "graphics-drawText-v1.0.5-sources.jar",
          "size": 1443,
          "sha512": "c4309ab904ae4a69a41402d8bed2f9470d3bedd8c46888ca4cb9ee94b4b888d3da0c83faae895059eafb1eee98411bfbb3f2c785cef89422462183c7d68bf0e5",
          "sha256": "9756f3c3b0e823a34c10e82fb5b511605be74f7783de5d1022eb591c752fccdc",
          "sha1": "592cea74f4554a1f537cbbc3c1e217bcc42bd684",
          "md5": "44b4e4e7d9451ae630c0ae70645e8162"
        }
      ]
    }
  ]
}
