{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "util-node",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "util-node-1.0.jar",
          "url": "util-node-1.0.jar",
          "size": 4394,
          "sha512": "92c022a31201a2f0bb85db37815ba967c00365850c6845b447e8453980224c1a20d639114cf973e79a85d19cefbc176042f7a8b5ce284afcf6d3c2a5e356146f",
          "sha256": "8307b51d34ab7d8a63b740121a94d8947103aad0fa3670991915c29762a54c0f",
          "sha1": "9ed59317723edef026db1d2f11bdf7d1b7e7e4ea",
          "md5": "58b3952cdd1a543bc3f6aeeb27d07d82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "util-node-1.0.jar",
          "url": "util-node-1.0.jar",
          "size": 4394,
          "sha512": "92c022a31201a2f0bb85db37815ba967c00365850c6845b447e8453980224c1a20d639114cf973e79a85d19cefbc176042f7a8b5ce284afcf6d3c2a5e356146f",
          "sha256": "8307b51d34ab7d8a63b740121a94d8947103aad0fa3670991915c29762a54c0f",
          "sha1": "9ed59317723edef026db1d2f11bdf7d1b7e7e4ea",
          "md5": "58b3952cdd1a543bc3f6aeeb27d07d82"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "util-node-1.0-sources.jar",
          "url": "util-node-1.0-sources.jar",
          "size": 1882,
          "sha512": "5cf029ec2af3c9242cea426ad91580598efe3b742ba67f7c5e5b4b0dc2d0231bdbdc6f34f64bde51380c87a93b2f68262d07d79864a061f55877c6f2b2899355",
          "sha256": "32ba7aebf2bc18b33777a15295d5ff738f17433445cd04ddae203a3de24b0e50",
          "sha1": "02eb9eed2aa9b5f24a4fb10fd8a3e1f80108ef98",
          "md5": "dd1b911b40e1c83e80d1d6c3ae62d288"
        }
      ]
    }
  ]
}
