{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.MindustryModCore",
    "module": "graphics",
    "version": "repo-test1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphics-repo-test1.jar",
          "url": "graphics-repo-test1.jar",
          "size": 7303,
          "sha512": "5d8ffaae1af26e741014768a5d8fc3657d67512921e67e4bd02e42d8eefd3a186a5ba293f6757752c58e25e79356ff9e61665967130bf6039bf326975e8f04ee",
          "sha256": "84fec5b75f5dd99f8e6fa32ef0fec0428f69f87273c0481d23ecfe6e3f6eb516",
          "sha1": "a404bf7412a7507683ae83d1e7c6003bde47459c",
          "md5": "0db795071ef1cae32bf38df960c23dd0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphics-repo-test1.jar",
          "url": "graphics-repo-test1.jar",
          "size": 7303,
          "sha512": "5d8ffaae1af26e741014768a5d8fc3657d67512921e67e4bd02e42d8eefd3a186a5ba293f6757752c58e25e79356ff9e61665967130bf6039bf326975e8f04ee",
          "sha256": "84fec5b75f5dd99f8e6fa32ef0fec0428f69f87273c0481d23ecfe6e3f6eb516",
          "sha1": "a404bf7412a7507683ae83d1e7c6003bde47459c",
          "md5": "0db795071ef1cae32bf38df960c23dd0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphics-repo-test1-sources.jar",
          "url": "graphics-repo-test1-sources.jar",
          "size": 3457,
          "sha512": "5b896866d0906da3512cd91ab3742617b5875d831a32e3fb434952fd45588b84e07622e5cd35ee5a6e46085526c3ae24e664f845e4bad432199b445b225795a2",
          "sha256": "e904f7b08b2a893b6501c4413cb5e4320bbb4276158d5b1f6985043c18814249",
          "sha1": "b476fe95ff58fcb0bef717d8b1ea98cb0379c0a8",
          "md5": "8c466c39b70bd36b1f627fcd412b3764"
        }
      ]
    }
  ]
}
