{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "utils",
    "version": "v1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "utils-v1.0.5.jar",
          "url": "utils-v1.0.5.jar",
          "size": 261,
          "sha512": "c0352715da1d421957548c7a661e3836291baf80641fdc121c622cd8c0b96db33c330bc7d077c8ae7ce295f5bbd0e863c9bb135fd2cc9958429979926c3920dd",
          "sha256": "417bc60d12622ee34e4627bd3ad2b51bc87f0148facc40b286c77b5f2d687a2e",
          "sha1": "7e99ca4a553c409210b733a6b6b607a3ec9743ea",
          "md5": "5295aa5fee6819651091fd12719b0cd6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-v1.0.5.jar",
          "url": "utils-v1.0.5.jar",
          "size": 261,
          "sha512": "c0352715da1d421957548c7a661e3836291baf80641fdc121c622cd8c0b96db33c330bc7d077c8ae7ce295f5bbd0e863c9bb135fd2cc9958429979926c3920dd",
          "sha256": "417bc60d12622ee34e4627bd3ad2b51bc87f0148facc40b286c77b5f2d687a2e",
          "sha1": "7e99ca4a553c409210b733a6b6b607a3ec9743ea",
          "md5": "5295aa5fee6819651091fd12719b0cd6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-v1.0.5-sources.jar",
          "url": "utils-v1.0.5-sources.jar",
          "size": 261,
          "sha512": "c0352715da1d421957548c7a661e3836291baf80641fdc121c622cd8c0b96db33c330bc7d077c8ae7ce295f5bbd0e863c9bb135fd2cc9958429979926c3920dd",
          "sha256": "417bc60d12622ee34e4627bd3ad2b51bc87f0148facc40b286c77b5f2d687a2e",
          "sha1": "7e99ca4a553c409210b733a6b6b607a3ec9743ea",
          "md5": "5295aa5fee6819651091fd12719b0cd6"
        }
      ]
    }
  ]
}
