{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "ui-components",
    "version": "v1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-components-v1.0.5.jar",
          "url": "ui-components-v1.0.5.jar",
          "size": 14477,
          "sha512": "f736654c4bcd14af8381c7cfc1a776850a6fb665eb061b13b1f5c5bb379bc49dcac5f45715e75a5c5480bc8c3aba9483bac74d7b26935dacea3e01a921cd92ad",
          "sha256": "0bd137ade19f9ce1b6cfc834069c062e139270a0ef81c2822ffdacc1b3df3322",
          "sha1": "903b35fff5971a0b15b2a0a010f37ef48a189f25",
          "md5": "f12e12965b2b1302fa399967a391cd1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-components-v1.0.5.jar",
          "url": "ui-components-v1.0.5.jar",
          "size": 14477,
          "sha512": "f736654c4bcd14af8381c7cfc1a776850a6fb665eb061b13b1f5c5bb379bc49dcac5f45715e75a5c5480bc8c3aba9483bac74d7b26935dacea3e01a921cd92ad",
          "sha256": "0bd137ade19f9ce1b6cfc834069c062e139270a0ef81c2822ffdacc1b3df3322",
          "sha1": "903b35fff5971a0b15b2a0a010f37ef48a189f25",
          "md5": "f12e12965b2b1302fa399967a391cd1e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-components-v1.0.5-sources.jar",
          "url": "ui-components-v1.0.5-sources.jar",
          "size": 4045,
          "sha512": "2fb20657503144fd64c6847a2e956de8753038989bb5ccc446192c0b8bd6c747193ed75b5542f44f0c832356b7fcd5f74b228c0216a1c3f514073d00bd82110f",
          "sha256": "7c051b556e976f1a148fbde91224cd813de1e1beab15d48bb87694f80a167c27",
          "sha1": "1f18f6c5488070b9b38dbaa27bc5c18d25944ed6",
          "md5": "4fb5c3a9376f268a0f1d0b2e3f5688a1"
        }
      ]
    }
  ]
}
