{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "betterCommandHandler",
    "version": "v1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.ArcLibrary",
          "module": "utils-pools",
          "version": {
            "requires": "v1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "betterCommandHandler-v1.0.5.jar",
          "url": "betterCommandHandler-v1.0.5.jar",
          "size": 37811,
          "sha512": "d9788a0f3a7e067fc3165c510a038772a86fdb706dab43da0d4ca958351c93365b93b05a8ae4e8115bc76695e567287fa4411d7b13ed296c4b2e495770f4aa05",
          "sha256": "c66a32396c24045889b7f6ce8daf81e01297d6efd1772aa14d323dbca60af3a8",
          "sha1": "b43bbc84eec8bccf2f0c1491f86c36b4c76b8428",
          "md5": "a456703f61f5baf34095ae3b48baa73d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.ArcLibrary",
          "module": "utils-pools",
          "version": {
            "requires": "v1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "betterCommandHandler-v1.0.5.jar",
          "url": "betterCommandHandler-v1.0.5.jar",
          "size": 37811,
          "sha512": "d9788a0f3a7e067fc3165c510a038772a86fdb706dab43da0d4ca958351c93365b93b05a8ae4e8115bc76695e567287fa4411d7b13ed296c4b2e495770f4aa05",
          "sha256": "c66a32396c24045889b7f6ce8daf81e01297d6efd1772aa14d323dbca60af3a8",
          "sha1": "b43bbc84eec8bccf2f0c1491f86c36b4c76b8428",
          "md5": "a456703f61f5baf34095ae3b48baa73d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterCommandHandler-v1.0.5-sources.jar",
          "url": "betterCommandHandler-v1.0.5-sources.jar",
          "size": 14045,
          "sha512": "259ffb65923e94cc64997fc628d9baaccb199c546ced33f4835fd25faa4dc422ee753e0061289210cdc062c4485fecd78f1c609fd2f450d9eb4f7e3ff4f722c5",
          "sha256": "d20702e44caeeae5d638670fc000125be25b3632079752ce5c391d8b4d31eacb",
          "sha1": "942ebc0ff6c50fa923f1ca8bcda1b2c70b2f3383",
          "md5": "3d340f8334f1e617bf8aab3df0a7691f"
        }
      ]
    }
  ]
}
