{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.MindustryModCore",
    "module": "blocks-customShapes",
    "version": "repo-test4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.ArcLibrary",
          "module": "graphics-extendedDraw",
          "version": {
            "requires": "v1.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "blocks-customShapes-repo-test4.jar",
          "url": "blocks-customShapes-repo-test4.jar",
          "size": 25298,
          "sha512": "f4a2b3c1c9c99dd51de4b359bbb565fa79fd1d37e618a6f2017dc30ab8fb40289bea0ab7744d15f6bc5cf2b1a94847841489f9c825002a7b77a5c879bf2cd522",
          "sha256": "c14cdc985f7841fe479f185e0dd3109659609decbeaaa1e35316ee28c883fce3",
          "sha1": "4c661b38bb11dcd8b4b050e1eddba1c6ffe20c03",
          "md5": "443a6c3deac2944ee5c4b11c7eb2fb44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.ArcLibrary",
          "module": "graphics-extendedDraw",
          "version": {
            "requires": "v1.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "blocks-customShapes-repo-test4.jar",
          "url": "blocks-customShapes-repo-test4.jar",
          "size": 25298,
          "sha512": "f4a2b3c1c9c99dd51de4b359bbb565fa79fd1d37e618a6f2017dc30ab8fb40289bea0ab7744d15f6bc5cf2b1a94847841489f9c825002a7b77a5c879bf2cd522",
          "sha256": "c14cdc985f7841fe479f185e0dd3109659609decbeaaa1e35316ee28c883fce3",
          "sha1": "4c661b38bb11dcd8b4b050e1eddba1c6ffe20c03",
          "md5": "443a6c3deac2944ee5c4b11c7eb2fb44"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blocks-customShapes-repo-test4-sources.jar",
          "url": "blocks-customShapes-repo-test4-sources.jar",
          "size": 7131,
          "sha512": "a9ad68954529dcc78477fa01fff81096911f64ac03677c4ec303f2c62d913bb6ab3df1f5f88278a6058496c4319b36961c3a8709823c5f7f4075563c5a085897",
          "sha256": "2a8893b89822a46243be2d85ce2d6b2ae92ba8ca3a8e6b498cf24a4440a8ff23",
          "sha1": "418fbc704e05770c609f3c50c6438ecad04f45ab",
          "md5": "42ddf902090787b0808952843bbec83e"
        },
        {
          "name": "blocks-customShapes-repo-test4-sources.jar",
          "url": "blocks-customShapes-repo-test4-sources.jar",
          "size": 7131,
          "sha512": "a9ad68954529dcc78477fa01fff81096911f64ac03677c4ec303f2c62d913bb6ab3df1f5f88278a6058496c4319b36961c3a8709823c5f7f4075563c5a085897",
          "sha256": "2a8893b89822a46243be2d85ce2d6b2ae92ba8ca3a8e6b498cf24a4440a8ff23",
          "sha1": "418fbc704e05770c609f3c50c6438ecad04f45ab",
          "md5": "42ddf902090787b0808952843bbec83e"
        }
      ]
    }
  ]
}
