{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "util-compile",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "util-compile-unspecified.jar",
          "url": "util-compile-unspecified.jar",
          "size": 3638,
          "sha512": "676e74e71e71538856f6417dbb365069504ddcd7292edd831dd3746813b7eb0b5e9c6a82ed72873b1b897654a995bd1b99f5e7beeb6f56daca0fa7818cba95a7",
          "sha256": "17115df86cb5b964059eacdd4763e1918756628950eae1c42a1640d5e6c64b24",
          "sha1": "653efe5f1c04151a3e5980b2c12cdf390275bcb7",
          "md5": "6764f3126ff37af3b2be3d01a28cc873"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "util-compile-unspecified.jar",
          "url": "util-compile-unspecified.jar",
          "size": 3638,
          "sha512": "676e74e71e71538856f6417dbb365069504ddcd7292edd831dd3746813b7eb0b5e9c6a82ed72873b1b897654a995bd1b99f5e7beeb6f56daca0fa7818cba95a7",
          "sha256": "17115df86cb5b964059eacdd4763e1918756628950eae1c42a1640d5e6c64b24",
          "sha1": "653efe5f1c04151a3e5980b2c12cdf390275bcb7",
          "md5": "6764f3126ff37af3b2be3d01a28cc873"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "util-compile-unspecified-sources.jar",
          "url": "util-compile-unspecified-sources.jar",
          "size": 2229,
          "sha512": "67dc367ba6ed9f5d8c3512542e3f2adbfaf0216e56ac0d41e6759f7a1bab562d054e394f4305e2aa6aac1f087f7976777df8b11f183beebf4a29e9a3726bbb45",
          "sha256": "e441495bf5b772c317eec90535540d5db5237eb4e086981be39a859ac58ab497",
          "sha1": "3e6dc36ad14e1e46b036ad9bfa05342b9156d82e",
          "md5": "efaf252075e5e2fa7d94cb38ea935dee"
        }
      ]
    }
  ]
}
