{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "ui-defaults",
    "version": "v1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-defaults-v1.0.3.jar",
          "url": "ui-defaults-v1.0.3.jar",
          "size": 8029,
          "sha512": "97705d212b65286e044da48bff2070e79560b33a6a8a19d863483829c325a948f4d2736398669e5d00045b22159a3d524486cd27a156360231d1d33d88dc45d4",
          "sha256": "db68b05a7398172a82015f3d55eabfd2e3252255fa7aa7aaeb76b5fb5c371033",
          "sha1": "94fcac07b5c1985ead04d8bc2aead18d7a1a11c4",
          "md5": "7fa7feab6c1dc8113894bb54ffe3a068"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-defaults-v1.0.3.jar",
          "url": "ui-defaults-v1.0.3.jar",
          "size": 8029,
          "sha512": "97705d212b65286e044da48bff2070e79560b33a6a8a19d863483829c325a948f4d2736398669e5d00045b22159a3d524486cd27a156360231d1d33d88dc45d4",
          "sha256": "db68b05a7398172a82015f3d55eabfd2e3252255fa7aa7aaeb76b5fb5c371033",
          "sha1": "94fcac07b5c1985ead04d8bc2aead18d7a1a11c4",
          "md5": "7fa7feab6c1dc8113894bb54ffe3a068"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-defaults-v1.0.3-sources.jar",
          "url": "ui-defaults-v1.0.3-sources.jar",
          "size": 1549,
          "sha512": "f02ecc76fe16454664eb2750246a1cbb929144a750f2cb33bfdb08284a2dddbffbd4ea8779eb3b3941585497d8eb9de4860934966da1f468cc9cae98441bb03a",
          "sha256": "fcfd417393ff09d1138b27b8ef961a9b17ce69a06e195dca82bdf5c5aef2feac",
          "sha1": "89157a5607f466683def582c97ec8596a7d65c84",
          "md5": "e2e71e48af03b721be0e93986a65bd28"
        }
      ]
    }
  ]
}
