{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "annotations-test",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "annotations-test-1.0.jar",
          "url": "annotations-test-1.0.jar",
          "size": 8856,
          "sha512": "2515db3fce4657dbc54b25aaf1701b9222e9de7ede26b15f86e9f9fc303c32673d5012774074a7d4b1efdbbbc339d71ba18771541f9ec468432a19f0ef3b3690",
          "sha256": "7a1faeb247e07f881c207e44c7d879b69375d5ab09d5a690d01adb17cf850898",
          "sha1": "9872dd7dcbe10bf4a312de24b903c93e77fa170b",
          "md5": "009a6b194f3c9d2726aee4989595e715"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "annotations-debug-print",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "annotations-method-bytecode",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-test-1.0.jar",
          "url": "annotations-test-1.0.jar",
          "size": 8856,
          "sha512": "2515db3fce4657dbc54b25aaf1701b9222e9de7ede26b15f86e9f9fc303c32673d5012774074a7d4b1efdbbbc339d71ba18771541f9ec468432a19f0ef3b3690",
          "sha256": "7a1faeb247e07f881c207e44c7d879b69375d5ab09d5a690d01adb17cf850898",
          "sha1": "9872dd7dcbe10bf4a312de24b903c93e77fa170b",
          "md5": "009a6b194f3c9d2726aee4989595e715"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-test-1.0-sources.jar",
          "url": "annotations-test-1.0-sources.jar",
          "size": 3414,
          "sha512": "d9039ff74d4e56e1eb999346eb43e09651971cb448dcfc9633640216ef21f5a882cbe2b0175a383249506aff5185f9ceeb71a78353ba8828fa65c5f91b2b30af",
          "sha256": "61a41e360cae101cec5775d8975ba581e69179235732a51d96b906d65ab1e71f",
          "sha1": "51fc80b11a7b64d41b6aba511a496a7626cb05ef",
          "md5": "ff6c12fc81ec8ce365568dcf03297176"
        }
      ]
    }
  ]
}
