{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.MindustryModCore",
    "module": "annotations",
    "version": "repo-test1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "annotations-repo-test1.jar",
          "url": "annotations-repo-test1.jar",
          "size": 14372981,
          "sha512": "4daa12726a2b0d6136e1fb1d1a5704d1c6b8ef6f1833beb76c78dc28e036a3b813e7033f0b52a26d2a338b33784196ccbfe83ac9518cbf6c9c9ca4b663348464",
          "sha256": "7db941a865bcb42ae28a6015c5df93ad2a595e20de78222e1cf73201d23c259f",
          "sha1": "fca064f39d594b41d346fb80701da65977f6999a",
          "md5": "265a07383e86f3c2f08e34ba8908a471"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v146"
          }
        },
        {
          "group": "com.github.Anuken.Mindustry",
          "module": "core",
          "version": {
            "requires": "v146"
          }
        },
        {
          "group": "com.github.javaparser",
          "module": "javaparser-symbol-solver-core",
          "version": {
            "requires": "3.22.1"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-repo-test1.jar",
          "url": "annotations-repo-test1.jar",
          "size": 14372981,
          "sha512": "4daa12726a2b0d6136e1fb1d1a5704d1c6b8ef6f1833beb76c78dc28e036a3b813e7033f0b52a26d2a338b33784196ccbfe83ac9518cbf6c9c9ca4b663348464",
          "sha256": "7db941a865bcb42ae28a6015c5df93ad2a595e20de78222e1cf73201d23c259f",
          "sha1": "fca064f39d594b41d346fb80701da65977f6999a",
          "md5": "265a07383e86f3c2f08e34ba8908a471"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-repo-test1-sources.jar",
          "url": "annotations-repo-test1-sources.jar",
          "size": 137500,
          "sha512": "7b6724b17d79724819e3e9bc20a3f70fb48640daf15346b92589e0dad14bb6cb1c643b424e2de5692f0f62b7e1465a58badd29f499a681f9efa56cac59b4b2a5",
          "sha256": "2b9b3920cdf407af02c3fd14dce23784227b1040f86ca07887fe4321a162b90a",
          "sha1": "25f5f570cc6467ffaf3b442ae2fd5008ab3cd5e7",
          "md5": "bcd7de3587debb11d0bb2561051ba657"
        }
      ]
    }
  ]
}
