{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "ui-tooltips",
    "version": "v1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-tooltips-v1.0.5.jar",
          "url": "ui-tooltips-v1.0.5.jar",
          "size": 4330,
          "sha512": "68024e77f4f0592272e9e46f60b0634064c90bfbd54db868e9214c9c9e3e928a12e328e2b35089c3ffc1523c9768b8a9747d73944f43d3b5b25a75e6536a8e5b",
          "sha256": "9428fd1eb14492b7f6ce062bd4cf1b450cfab414dc68d18a203741bd32070505",
          "sha1": "111e2e0a51c4cfd1cb1509730105b2828e0c3815",
          "md5": "e8b81e39468559733aae16fb5c2f721d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-tooltips-v1.0.5.jar",
          "url": "ui-tooltips-v1.0.5.jar",
          "size": 4330,
          "sha512": "68024e77f4f0592272e9e46f60b0634064c90bfbd54db868e9214c9c9e3e928a12e328e2b35089c3ffc1523c9768b8a9747d73944f43d3b5b25a75e6536a8e5b",
          "sha256": "9428fd1eb14492b7f6ce062bd4cf1b450cfab414dc68d18a203741bd32070505",
          "sha1": "111e2e0a51c4cfd1cb1509730105b2828e0c3815",
          "md5": "e8b81e39468559733aae16fb5c2f721d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-tooltips-v1.0.5-sources.jar",
          "url": "ui-tooltips-v1.0.5-sources.jar",
          "size": 2081,
          "sha512": "ca068c0c55c1a4262c18dc80383f90eefa303f610792e99b7b28c579fddc90411bc8373d1a7e02beda3fda4917911b772943e34e3c3bf49fa6463e9809164706",
          "sha256": "2620ff4cc50b4146cfc6933ec4ab9f562713a555399dc627407152388a2604e3",
          "sha1": "c02a8180857213a387dba0cbbe8dbb4c3faa379e",
          "md5": "003cacde362a935f6cc2e71093486b03"
        }
      ]
    }
  ]
}
