{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "ui-tooltips",
    "version": "v1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-tooltips-v1.0.5.jar",
          "url": "ui-tooltips-v1.0.5.jar",
          "size": 4330,
          "sha512": "c26b9652e89e9ecebfbc03c631ff227daccc59aa0831da4cfb592e76e68dc04131fb30af74268537782b47d650bf407be06c885893c4d407b6a5086a1caa9a4b",
          "sha256": "2e620a17821e71b1767c078a1d235f94ec4366027c30059f9214dfc6c60b9ac2",
          "sha1": "d05294726a18187e7ea89a72fbdcd50a69157aae",
          "md5": "67a763feb4a917712198f865140be813"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-tooltips-v1.0.5.jar",
          "url": "ui-tooltips-v1.0.5.jar",
          "size": 4330,
          "sha512": "c26b9652e89e9ecebfbc03c631ff227daccc59aa0831da4cfb592e76e68dc04131fb30af74268537782b47d650bf407be06c885893c4d407b6a5086a1caa9a4b",
          "sha256": "2e620a17821e71b1767c078a1d235f94ec4366027c30059f9214dfc6c60b9ac2",
          "sha1": "d05294726a18187e7ea89a72fbdcd50a69157aae",
          "md5": "67a763feb4a917712198f865140be813"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-tooltips-v1.0.5-sources.jar",
          "url": "ui-tooltips-v1.0.5-sources.jar",
          "size": 2081,
          "sha512": "1ca50bff50761af6a02d596a32064d86ee75d8ac0d9b8dfe44d8a6c975ab1cbf6dd3252e843afe8ab47f17241769dc0ce7084a3bcd211e196fa7cc86d40230b2",
          "sha256": "b001fea55cb0cf29be1e8ce502da86376ba1dfa7527af6a6dc7dcf5affcb3974",
          "sha1": "e43a311a17409861ef66b85729c340c1ada61f3e",
          "md5": "e2a0e20d2435a1ff98f662d9938c3851"
        }
      ]
    }
  ]
}
