{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "ui-tooltips-kt",
    "version": "v1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooltips-kt-v1.0.5.jar",
          "url": "ui-tooltips-kt-v1.0.5.jar",
          "size": 2254,
          "sha512": "b43a7c271191bedd52dc0728c21bc4d171c81f3384b7e7fe8291dd141e78a14a355f41c3049d69412cd449601663f63c026fa103ee6a491424b2b18ee86251cf",
          "sha256": "aede7aa40e3ec5fd3fc5c39650563747602a844f8bf7fcddba612bd2682ffae6",
          "sha1": "66d952bc690d7fca5fd2a36f9f433b70f79f9f10",
          "md5": "c1e6c160dbc4923a884565e9eb2ee33a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.ArcLibrary",
          "module": "ui-tooltips",
          "version": {
            "requires": "v1.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooltips-kt-v1.0.5.jar",
          "url": "ui-tooltips-kt-v1.0.5.jar",
          "size": 2254,
          "sha512": "b43a7c271191bedd52dc0728c21bc4d171c81f3384b7e7fe8291dd141e78a14a355f41c3049d69412cd449601663f63c026fa103ee6a491424b2b18ee86251cf",
          "sha256": "aede7aa40e3ec5fd3fc5c39650563747602a844f8bf7fcddba612bd2682ffae6",
          "sha1": "66d952bc690d7fca5fd2a36f9f433b70f79f9f10",
          "md5": "c1e6c160dbc4923a884565e9eb2ee33a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-tooltips-kt-v1.0.5-sources.jar",
          "url": "ui-tooltips-kt-v1.0.5-sources.jar",
          "size": 963,
          "sha512": "3bab1d374864cba228596f99210d0eb1f0bce1cb138fb90dec207f58d0d552518a32522102603bf35bb89507669f87f52952f5543bf101d9c09f8befd5dc3fde",
          "sha256": "175b946832782165d9817049becc52ac159350240e48c0e523af3a896405874a",
          "sha1": "249719c3c950ed5ff3b7f1627523fba6fae524d9",
          "md5": "07dc706088d3300909a68f6c69900cd1"
        }
      ]
    }
  ]
}
