{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.MindustryModCore",
    "module": "mindustryModGradlePlugin",
    "version": "repo-test1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mindustryModGradlePlugin-repo-test1.jar",
          "url": "mindustryModGradlePlugin-repo-test1.jar",
          "size": 1274486,
          "sha512": "4224a20a70a8ce077ab9e61c07b3d436247dadb904523ac9b3e84720893604078ad4a655eec5b3c1b9ad09c393a14c6e29f5ce0d65faa00caafb8c5230d7ccc8",
          "sha256": "7b9c46233ad76cb644d63d41ab7be127954734e30b3f9b3d2d6c558359063f50",
          "sha1": "be25e36731110cf61d9a2c1f8ad03ae2a149de4d",
          "md5": "cefc0a1b62ffd7fabf91cc7f0c41c738"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v146"
          }
        },
        {
          "group": "org.jetbrains.kotlin.jvm",
          "module": "org.jetbrains.kotlin.jvm.gradle.plugin",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin.kapt",
          "module": "org.jetbrains.kotlin.kapt.gradle.plugin",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "mindustryModGradlePlugin-repo-test1.jar",
          "url": "mindustryModGradlePlugin-repo-test1.jar",
          "size": 1274486,
          "sha512": "4224a20a70a8ce077ab9e61c07b3d436247dadb904523ac9b3e84720893604078ad4a655eec5b3c1b9ad09c393a14c6e29f5ce0d65faa00caafb8c5230d7ccc8",
          "sha256": "7b9c46233ad76cb644d63d41ab7be127954734e30b3f9b3d2d6c558359063f50",
          "sha1": "be25e36731110cf61d9a2c1f8ad03ae2a149de4d",
          "md5": "cefc0a1b62ffd7fabf91cc7f0c41c738"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mindustryModGradlePlugin-repo-test1-sources.jar",
          "url": "mindustryModGradlePlugin-repo-test1-sources.jar",
          "size": 15895,
          "sha512": "0a0f8c744b87f0238926644c90fc115447daad5873c7df89dcdf8c6ca225c0c8ebac10674ed20eec19b1da4d69aa40f73adead585024024953acc6aa55daf1b7",
          "sha256": "ffc2541a64f695cf7da9ce044c57ba61784e0818206becd20fb8267873c7c283",
          "sha1": "6cf813206cb293f7399e66aa1dbe3cfdbaef4973",
          "md5": "511309bfda9e4980e099e6b8eb0f36c3"
        }
      ]
    }
  ]
}
