{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.MindustryModCore",
    "module": "blocks-smartDistrubution",
    "version": "v2.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.ArcLibrary",
          "module": "graphics-extendedDraw",
          "version": {
            "requires": "v1.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "blocks-smartDistrubution-v2.0.3.jar",
          "url": "blocks-smartDistrubution-v2.0.3.jar",
          "size": 25469,
          "sha512": "9e79755dcc2aba8fc1e0994deb21f7d0ad993a73fd1892160bdabe540147e39232aec5db92bed7e4e654bb5d4d124eec9d5d364b01f0d894f6f575c43671ae35",
          "sha256": "5e3b3dc8924a627a07c00fff33968aa18a093d815974acccab8f22d41bc13e0d",
          "sha1": "c5042da87c22afe8d30a6e248fe595026e799fa1",
          "md5": "c6d1a32c3cf91c86b9eeca1b619855f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.ArcLibrary",
          "module": "graphics-extendedDraw",
          "version": {
            "requires": "v1.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "blocks-smartDistrubution-v2.0.3.jar",
          "url": "blocks-smartDistrubution-v2.0.3.jar",
          "size": 25469,
          "sha512": "9e79755dcc2aba8fc1e0994deb21f7d0ad993a73fd1892160bdabe540147e39232aec5db92bed7e4e654bb5d4d124eec9d5d364b01f0d894f6f575c43671ae35",
          "sha256": "5e3b3dc8924a627a07c00fff33968aa18a093d815974acccab8f22d41bc13e0d",
          "sha1": "c5042da87c22afe8d30a6e248fe595026e799fa1",
          "md5": "c6d1a32c3cf91c86b9eeca1b619855f5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blocks-smartDistrubution-v2.0.3-sources.jar",
          "url": "blocks-smartDistrubution-v2.0.3-sources.jar",
          "size": 7465,
          "sha512": "dfdd628a91ecda12a5d00b5061658196073cf95bb37cdb0dd1a79ebe564ea7fba00c1083a79c82a7c0057327c70f68d11b4123903f0aa48e2f1afb014bcaa1f4",
          "sha256": "d84a2e7eb1ac45dd71266051114e8b7980eba9028dc22aeeb6fcfbc98690e031",
          "sha1": "cb4747733220e4a4b502150822aa0813c419bcdb",
          "md5": "96881b0de40b50f1e3b37f812b000f67"
        },
        {
          "name": "blocks-smartDistrubution-v2.0.3-sources.jar",
          "url": "blocks-smartDistrubution-v2.0.3-sources.jar",
          "size": 7465,
          "sha512": "dfdd628a91ecda12a5d00b5061658196073cf95bb37cdb0dd1a79ebe564ea7fba00c1083a79c82a7c0057327c70f68d11b4123903f0aa48e2f1afb014bcaa1f4",
          "sha256": "d84a2e7eb1ac45dd71266051114e8b7980eba9028dc22aeeb6fcfbc98690e031",
          "sha1": "cb4747733220e4a4b502150822aa0813c419bcdb",
          "md5": "96881b0de40b50f1e3b37f812b000f67"
        }
      ]
    }
  ]
}
