{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.MindustryModCore",
    "module": "annotations-dependencies",
    "version": "v2.0.3a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "annotations-dependencies-v2.0.3a.jar",
          "url": "annotations-dependencies-v2.0.3a.jar",
          "size": 14175178,
          "sha512": "e731de5244d8644ad3b3f99a4df2fb60fd2370b3e7b05ff9430d82a68abae122bb2327e770050fb19242e646d5eea6fc337a2196fb2269b4b79422bdaeb22f82",
          "sha256": "411e0578e213a8c148967b9afbb5ab15d8dd2cf751d7dc77a9cc7116055a8bd6",
          "sha1": "9ff16ce9a5b3400dbe20a0aef4fadef27f76ee9b",
          "md5": "1c88ae754dd423bc43174e4adb2a626e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "com.github.Zelaux.MindustryModCore",
          "module": "annotations-mindustry",
          "version": {
            "requires": "v2.0.3a"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.github.Anuken.Arc",
          "module": "arc-core",
          "version": {
            "requires": "v146"
          }
        },
        {
          "group": "com.github.Anuken.Mindustry",
          "module": "core",
          "version": {
            "requires": "v146"
          }
        },
        {
          "group": "com.github.javaparser",
          "module": "javaparser-symbol-solver-core",
          "version": {
            "requires": "3.22.1"
          }
        },
        {
          "group": "com.github.Zelaux.MindustryModCore",
          "module": "annotations-common",
          "version": {
            "requires": "v2.0.3a"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-dependencies-v2.0.3a.jar",
          "url": "annotations-dependencies-v2.0.3a.jar",
          "size": 14175178,
          "sha512": "e731de5244d8644ad3b3f99a4df2fb60fd2370b3e7b05ff9430d82a68abae122bb2327e770050fb19242e646d5eea6fc337a2196fb2269b4b79422bdaeb22f82",
          "sha256": "411e0578e213a8c148967b9afbb5ab15d8dd2cf751d7dc77a9cc7116055a8bd6",
          "sha1": "9ff16ce9a5b3400dbe20a0aef4fadef27f76ee9b",
          "md5": "1c88ae754dd423bc43174e4adb2a626e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-dependencies-v2.0.3a-sources.jar",
          "url": "annotations-dependencies-v2.0.3a-sources.jar",
          "size": 2493,
          "sha512": "7031849ff9f1711399ff2d3ec8ed43139f09740a9fd52bf93e0aa957c83df20d3368625320fe0bca6ffbb6a0ba4be0b95503434265e49016d55826e6e8d80503",
          "sha256": "064e66fb50e4796a4720d278d61129b7563d56bdc51202500dbdb2e3935db785",
          "sha1": "baed317ffdcf110a25bfd03a60e2aa88a5f9838f",
          "md5": "4f4f1ab8ce281595f3b5ed8aad720612"
        }
      ]
    }
  ]
}
