{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "util-node",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "util-node-unspecified.jar",
          "url": "util-node-unspecified.jar",
          "size": 4394,
          "sha512": "301f483df772fc23ef0644c6b34c33b3fee86183cf4253dbaccc0142ccd489ea27ebe83a5d9ede8ee6dd1b007b7235a781eb719d926b099dd4430faebd49f7af",
          "sha256": "b5796f0373a1e12e913aa021e2c740d3837aee27e4381cfb2160155031b200ca",
          "sha1": "be066690466c0d88c27b93a608f520d845754589",
          "md5": "ab6afe252640acdf1c8efdb4911bd656"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "util-node-unspecified.jar",
          "url": "util-node-unspecified.jar",
          "size": 4394,
          "sha512": "301f483df772fc23ef0644c6b34c33b3fee86183cf4253dbaccc0142ccd489ea27ebe83a5d9ede8ee6dd1b007b7235a781eb719d926b099dd4430faebd49f7af",
          "sha256": "b5796f0373a1e12e913aa021e2c740d3837aee27e4381cfb2160155031b200ca",
          "sha1": "be066690466c0d88c27b93a608f520d845754589",
          "md5": "ab6afe252640acdf1c8efdb4911bd656"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "util-node-unspecified-sources.jar",
          "url": "util-node-unspecified-sources.jar",
          "size": 1882,
          "sha512": "4acf4038a074189032490855e1ca70aa67674925f8f7abb8bb32310066c7e65648312eb206c8b01ba60eb28cc8ca193235159129436b3b9fc9601c9bf29c3acc",
          "sha256": "274c35e431ef9e4de1eb2b5669385d5edf0f8885975f999d23503f773a43b7c8",
          "sha1": "b86c230d6c9c2371911992e86f1e1b1f79b8b705",
          "md5": "56496bf7d481b286040408e80ce6d251"
        }
      ]
    }
  ]
}
