{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.MindustryModCore",
    "module": "utils",
    "version": "repo-test1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "utils-repo-test1.jar",
          "url": "utils-repo-test1.jar",
          "size": 9640,
          "sha512": "b40f6f8559c680ad1807a554225d0a1ced3049a2acb20bcf3413c937b606b7a3a1212f776daab99467d8c66b4638a58d2cf2575132f9c2d288ec2479296be594",
          "sha256": "c1736814ea5ebebe68d327fd7de85e9d7a9cd6fd8f07eb8b27f7712b95f0b902",
          "sha1": "951a224d7559925319bfd2ceeff2f0d38249735f",
          "md5": "0840a33f77e7dcaa20004a3041225eff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-repo-test1.jar",
          "url": "utils-repo-test1.jar",
          "size": 9640,
          "sha512": "b40f6f8559c680ad1807a554225d0a1ced3049a2acb20bcf3413c937b606b7a3a1212f776daab99467d8c66b4638a58d2cf2575132f9c2d288ec2479296be594",
          "sha256": "c1736814ea5ebebe68d327fd7de85e9d7a9cd6fd8f07eb8b27f7712b95f0b902",
          "sha1": "951a224d7559925319bfd2ceeff2f0d38249735f",
          "md5": "0840a33f77e7dcaa20004a3041225eff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-repo-test1-sources.jar",
          "url": "utils-repo-test1-sources.jar",
          "size": 4798,
          "sha512": "3e36d4593ccf9efb4f3fa2d06b97092f70f25031c34f49b7c6cd6f921e11200e41b4945eeee4ea7b2f2a2dd4890ae6549edd6a1589dcc9d2e4f542ac83902f31",
          "sha256": "323a9ff6ae5a1811d4e95e998fe4273e8ea4db16fe2fc8a5efcdf00f4e9f26b0",
          "sha1": "5f983562979cc7aae3ecd66760b25e6273c6dbf7",
          "md5": "6b37c3fe48a62a816e89b20804824f65"
        }
      ]
    }
  ]
}
