{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "annotations-lombok-plugin-starter",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "annotations-lombok-plugin-starter-unspecified.jar",
          "url": "annotations-lombok-plugin-starter-unspecified.jar",
          "size": 40354,
          "sha512": "44dda3b11b1bc12cbe7e04695a4e2f903aaaf50e95aee01978eca24cee51616e3e6f82e36ea42ae5c1c7cc3eeb5930d4d21d90a6e883e4cdeb149aecb867db87",
          "sha256": "604ed4ce5243c69abc5f5698a1e165d0c0e2b8dfd8b2908b58a049680cec9258",
          "sha1": "cedd453923770c004deee45355cd321611c1173a",
          "md5": "f2c6bd966c59649a3a8e3aa6defbed04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "com.github.javaparser",
          "module": "javaparser-symbol-solver-core",
          "version": {
            "requires": "3.26.0"
          }
        },
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "util-classfile-metadata",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-lombok-plugin-starter-unspecified.jar",
          "url": "annotations-lombok-plugin-starter-unspecified.jar",
          "size": 40354,
          "sha512": "44dda3b11b1bc12cbe7e04695a4e2f903aaaf50e95aee01978eca24cee51616e3e6f82e36ea42ae5c1c7cc3eeb5930d4d21d90a6e883e4cdeb149aecb867db87",
          "sha256": "604ed4ce5243c69abc5f5698a1e165d0c0e2b8dfd8b2908b58a049680cec9258",
          "sha1": "cedd453923770c004deee45355cd321611c1173a",
          "md5": "f2c6bd966c59649a3a8e3aa6defbed04"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-lombok-plugin-starter-unspecified-sources.jar",
          "url": "annotations-lombok-plugin-starter-unspecified-sources.jar",
          "size": 14380,
          "sha512": "ec533a91f69cd83533ee29f1f7b79c4bb9299be6e7aa31185ac6402f1febcede7bbf2434b8c522a3fa80246c55bc2f0210cd4d3ace783fb357288852655c83b7",
          "sha256": "6d05e2f1bc1435a7d257d2aa8f62f08bfe5000c829bd3af163b36cb2b9a9d9f4",
          "sha1": "07ec9d1d9be0e735f55732811ecd406d44cf7cd6",
          "md5": "69e64bfd6697cf6d6ee7cbc929277e16"
        }
      ]
    }
  ]
}
