{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "util-method",
    "version": "v0.9.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "util-method-v0.9.7.jar",
          "url": "util-method-v0.9.7.jar",
          "size": 3443,
          "sha512": "7c6e4c6ab8c303969b516c20f14fdf9957c9b5e50a884da48401de05ba703679283b58efeb6756dd3b84db045942541abd3f7618c38c79786e3d5ffa0dc883af",
          "sha256": "f0e7961cd4fb57e100e0bcd8478a2233dd5651ab5c0ad1f46c4d4913934e95b2",
          "sha1": "60e843a7ec977c070c99a9bbcd08d1571a80fa38",
          "md5": "e2230362cecfe6f857cd776f904adf82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "util-method-v0.9.7.jar",
          "url": "util-method-v0.9.7.jar",
          "size": 3443,
          "sha512": "7c6e4c6ab8c303969b516c20f14fdf9957c9b5e50a884da48401de05ba703679283b58efeb6756dd3b84db045942541abd3f7618c38c79786e3d5ffa0dc883af",
          "sha256": "f0e7961cd4fb57e100e0bcd8478a2233dd5651ab5c0ad1f46c4d4913934e95b2",
          "sha1": "60e843a7ec977c070c99a9bbcd08d1571a80fa38",
          "md5": "e2230362cecfe6f857cd776f904adf82"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "util-method-v0.9.7-sources.jar",
          "url": "util-method-v0.9.7-sources.jar",
          "size": 1928,
          "sha512": "688e55db724f803ec0532216a5cc6bbc741386585de70da6540aaaf5e3e55749d7267881b570e27f524373cc7b3108979f639e2339f77e92b129d7cd73bfdc27",
          "sha256": "aa9a42e8049536ed74a3975e5ee9e399d1dad15f73aabd88227a4c69176a3561",
          "sha1": "f5925fa49c156d3c82e4e37548411945fae993b6",
          "md5": "9dc8fc39df360ba0f6d64bb2ae5cf647"
        }
      ]
    }
  ]
}
