{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.MindustryModCore",
    "module": "blocks-consumers",
    "version": "v2.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.ArcLibrary",
          "module": "graphics-extendedDraw",
          "version": {
            "requires": "v1.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "blocks-consumers-v2.0.3.jar",
          "url": "blocks-consumers-v2.0.3.jar",
          "size": 9768,
          "sha512": "e22aa4f6af1a1b78ac4282e27b707cb38ca499b8ea60e40d1acce5448c7c368e4eab74870cc54d33f2a57202e93afe98d9c788dec03df5c3e06d777bbee64585",
          "sha256": "05b154549126fa96b9d6126d963b1a7d4c9fd4af0d9095e60119a49620dff9a3",
          "sha1": "42700433ea7c3bc340ef939a496bdb4ad60a666c",
          "md5": "34990b0d05636c5d7a7094aa0bd85824"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.ArcLibrary",
          "module": "graphics-extendedDraw",
          "version": {
            "requires": "v1.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "blocks-consumers-v2.0.3.jar",
          "url": "blocks-consumers-v2.0.3.jar",
          "size": 9768,
          "sha512": "e22aa4f6af1a1b78ac4282e27b707cb38ca499b8ea60e40d1acce5448c7c368e4eab74870cc54d33f2a57202e93afe98d9c788dec03df5c3e06d777bbee64585",
          "sha256": "05b154549126fa96b9d6126d963b1a7d4c9fd4af0d9095e60119a49620dff9a3",
          "sha1": "42700433ea7c3bc340ef939a496bdb4ad60a666c",
          "md5": "34990b0d05636c5d7a7094aa0bd85824"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blocks-consumers-v2.0.3-sources.jar",
          "url": "blocks-consumers-v2.0.3-sources.jar",
          "size": 1457,
          "sha512": "120a071794659fb0b3d4c6f276a7f9270a012a3cdaffc7e9e416b55afc46651f7629e9cc33563486ab93beda29f16e677d0f7033237bd59c6bb505a7982f78ed",
          "sha256": "eb42a9d03db4fba06ead8e64662ca58f175cf6ffa95585faaa12aa14c965ca35",
          "sha1": "7cfb519b6d2bbc42694cf21ee8437397ae847914",
          "md5": "843bb70111e15f896a9af0f44c4b0783"
        },
        {
          "name": "blocks-consumers-v2.0.3-sources.jar",
          "url": "blocks-consumers-v2.0.3-sources.jar",
          "size": 1457,
          "sha512": "120a071794659fb0b3d4c6f276a7f9270a012a3cdaffc7e9e416b55afc46651f7629e9cc33563486ab93beda29f16e677d0f7033237bd59c6bb505a7982f78ed",
          "sha256": "eb42a9d03db4fba06ead8e64662ca58f175cf6ffa95585faaa12aa14c965ca35",
          "sha1": "7cfb519b6d2bbc42694cf21ee8437397ae847914",
          "md5": "843bb70111e15f896a9af0f44c4b0783"
        }
      ]
    }
  ]
}
