{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "annotations-debug-print",
    "version": "v0.9.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "annotations-lombok-plugin-starter",
          "version": {
            "requires": "v0.9.5"
          }
        },
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "annotations-unshadowed-lombok",
          "version": {
            "requires": "v0.9.5"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-debug-print-v0.9.5.jar",
          "url": "annotations-debug-print-v0.9.5.jar",
          "size": 12520,
          "sha512": "a197e5244791c2b444654734595a2905bca3617cec953a9f218171c9b85162ca5c7e96fb52fd91b615a3083e9f50a3444b76a63d12f0a57e115f3da06869722b",
          "sha256": "70c4da2e9b9f6bdd4fbcb6f760f8f2f4552834013ed1c0875d323230e27add93",
          "sha1": "a5257137019bc3801d32f920fc5bb755f89f4481",
          "md5": "570d9ca31e8e20ae042318be0262fde8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "util-classfile-metadata",
          "version": {
            "requires": "v0.9.5"
          }
        },
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "util-node",
          "version": {
            "requires": "v0.9.5"
          }
        },
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "annotations-lombok-plugin-starter",
          "version": {
            "requires": "v0.9.5"
          }
        }
      ],
      "files": [
        {
          "name": "annotations-debug-print-v0.9.5.jar",
          "url": "annotations-debug-print-v0.9.5.jar",
          "size": 12520,
          "sha512": "a197e5244791c2b444654734595a2905bca3617cec953a9f218171c9b85162ca5c7e96fb52fd91b615a3083e9f50a3444b76a63d12f0a57e115f3da06869722b",
          "sha256": "70c4da2e9b9f6bdd4fbcb6f760f8f2f4552834013ed1c0875d323230e27add93",
          "sha1": "a5257137019bc3801d32f920fc5bb755f89f4481",
          "md5": "570d9ca31e8e20ae042318be0262fde8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-debug-print-v0.9.5-sources.jar",
          "url": "annotations-debug-print-v0.9.5-sources.jar",
          "size": 5562,
          "sha512": "a63cd85c9a8e94a946cef76f5cb1bdcfae4c8d331ae6028f80c155d69fff9b74e482a4a07f00d2f527d263126a85bdcd28fd327867f0a5d7a385e918b5b530be",
          "sha256": "64b8f8674349172b5b80df6c38d1a73e7143836a0b5ec1b98913cb9f2918880e",
          "sha1": "71ef044ee5a199de2a925e7e332a89b348149ee7",
          "md5": "2fd4536f0297d3532fa437b793f88c2d"
        }
      ]
    }
  ]
}
