{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "betterCommandHandler",
    "version": "v1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.ArcLibrary",
          "module": "utils-pools",
          "version": {
            "requires": "v1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "betterCommandHandler-v1.0.1.jar",
          "url": "betterCommandHandler-v1.0.1.jar",
          "size": 35850,
          "sha512": "9c50b662c2c00d9b6f852034e445d76709cb1e6a2831df03a8cfef0e9908f7f03246793e77daef9845c28ff7bcdf1f44f10c60084111bf276eaf0910f39320d4",
          "sha256": "66993b64a28fa037d983d91999e80aeb36fb593904a4e75916d137feeae4515b",
          "sha1": "4848e41a1b385575d944558f3f9e696c34e72c28",
          "md5": "2d57f3d475d163f6c3b10bc2103d48eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.ArcLibrary",
          "module": "utils-pools",
          "version": {
            "requires": "v1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "betterCommandHandler-v1.0.1.jar",
          "url": "betterCommandHandler-v1.0.1.jar",
          "size": 35850,
          "sha512": "9c50b662c2c00d9b6f852034e445d76709cb1e6a2831df03a8cfef0e9908f7f03246793e77daef9845c28ff7bcdf1f44f10c60084111bf276eaf0910f39320d4",
          "sha256": "66993b64a28fa037d983d91999e80aeb36fb593904a4e75916d137feeae4515b",
          "sha1": "4848e41a1b385575d944558f3f9e696c34e72c28",
          "md5": "2d57f3d475d163f6c3b10bc2103d48eb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "betterCommandHandler-v1.0.1-sources.jar",
          "url": "betterCommandHandler-v1.0.1-sources.jar",
          "size": 13109,
          "sha512": "00370c4428db2bc055c286031e80f01f30de50d13c4e2012afd45cc778a55e615993a6e04871d5af03bf2235b779cf0f8f6f1212c607fd4124a537e0059d6e8d",
          "sha256": "8ccdda3aee0a2e5f43180ff118fa70edddb3472f7e2a650082a2f2a1c015a62e",
          "sha1": "a2c414de71d738b162031ba7720e4c47493bcb31",
          "md5": "fc6dc32bb2ecdc2fe88524a34e0d78c0"
        }
      ]
    }
  ]
}
