{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "graphics-g3d",
    "version": "v1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "graphics-g3d-v1.0.5.jar",
          "url": "graphics-g3d-v1.0.5.jar",
          "size": 15924,
          "sha512": "16915a25d9eab8d5c719a6b2e93d860ad3269df7907fcb89283a577671add0c465dbb598d8838a375b4443a7d80452032e92675cd06eba5795c0eadd066c9b84",
          "sha256": "ec0cf53ada6ef4be1e3a8fe5eb8761a1b3cc57f0e86ad5728d091b8c8405ae02",
          "sha1": "781fc11b816d9414806a2c3cfa2225df6167d24e",
          "md5": "fc3e7e5e723625762e5b0006ce7f44e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphics-g3d-v1.0.5.jar",
          "url": "graphics-g3d-v1.0.5.jar",
          "size": 15924,
          "sha512": "16915a25d9eab8d5c719a6b2e93d860ad3269df7907fcb89283a577671add0c465dbb598d8838a375b4443a7d80452032e92675cd06eba5795c0eadd066c9b84",
          "sha256": "ec0cf53ada6ef4be1e3a8fe5eb8761a1b3cc57f0e86ad5728d091b8c8405ae02",
          "sha1": "781fc11b816d9414806a2c3cfa2225df6167d24e",
          "md5": "fc3e7e5e723625762e5b0006ce7f44e5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphics-g3d-v1.0.5-sources.jar",
          "url": "graphics-g3d-v1.0.5-sources.jar",
          "size": 8486,
          "sha512": "61a1f9393d51552f7222b3112a34e1270a4e449238b47196d1a57271a846b9d4a91de8fea4c93daac0daef4627b70386b0a3ee3acd094e1cba24c3805fb93b8c",
          "sha256": "f6f35ef09ce1e5e200144faaebf0b7f2b38591f51e51f604ee3f1502920ec573",
          "sha1": "84ba233af4337eeb286b337f08edd58f1c7df016",
          "md5": "521884ea95c7469e9e3bfcc66cd42cd7"
        }
      ]
    }
  ]
}
