{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "ui-utils",
    "version": "v1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-utils-v1.0.5.jar",
          "url": "ui-utils-v1.0.5.jar",
          "size": 8237,
          "sha512": "8b7ff28e79492d2725d90978bc92c29c2fad518ea39cd9b749a446c293eebc60e77e22920599fd7d7a526cc14e7567391fa1f8964e9c9929d750f101c2ce11b7",
          "sha256": "ef9bc2a226f22a2a629b5f2c09082b494d5430a65fa2845989eee9fa3f854610",
          "sha1": "cd617b38ab4936a19b4bc80fd28ebf6a6fe7a0e6",
          "md5": "00c7f0ea15cab03134cd83dc845ad53f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-utils-v1.0.5.jar",
          "url": "ui-utils-v1.0.5.jar",
          "size": 8237,
          "sha512": "8b7ff28e79492d2725d90978bc92c29c2fad518ea39cd9b749a446c293eebc60e77e22920599fd7d7a526cc14e7567391fa1f8964e9c9929d750f101c2ce11b7",
          "sha256": "ef9bc2a226f22a2a629b5f2c09082b494d5430a65fa2845989eee9fa3f854610",
          "sha1": "cd617b38ab4936a19b4bc80fd28ebf6a6fe7a0e6",
          "md5": "00c7f0ea15cab03134cd83dc845ad53f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-utils-v1.0.5-sources.jar",
          "url": "ui-utils-v1.0.5-sources.jar",
          "size": 3500,
          "sha512": "2537254a2fa7fdd4ca67007ec7142a3f05b9e24b51d258fd0c60dbe6a0b4bf6f32adf70c23d4ef89d8c15f72a871b3a3b453adf92a5c5a7be49bc11be74694b9",
          "sha256": "53fa10128be98fd4144a9259b0ed080e5efebdd517a98dfdcd90c0c735729714",
          "sha1": "161a54a31db820af67d6f9ac304d7ebf18e6c4bc",
          "md5": "38274c4476e4b22397ae874cd89c5bba"
        }
      ]
    }
  ]
}
