{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "settings",
    "version": "v1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "settings-v1.0.5.jar",
          "url": "settings-v1.0.5.jar",
          "size": 18395,
          "sha512": "bccb778cd3ec5b1bc06ee4217318b7bb8d8c13d3365bfc0046e586c6ea176609a47bb45e18a9a328a62e4084584488e976f2810bcd166c52ec65ad58c8d012db",
          "sha256": "293fb41bbd7d8049d16798eefa5a419aacdca930a8576eb827aa94788b033b60",
          "sha1": "08a4ba759187c65f74c5a6b47b9d53a89a5b392a",
          "md5": "2a55fe2a54927e7fd152169024a7d4f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "settings-v1.0.5.jar",
          "url": "settings-v1.0.5.jar",
          "size": 18395,
          "sha512": "bccb778cd3ec5b1bc06ee4217318b7bb8d8c13d3365bfc0046e586c6ea176609a47bb45e18a9a328a62e4084584488e976f2810bcd166c52ec65ad58c8d012db",
          "sha256": "293fb41bbd7d8049d16798eefa5a419aacdca930a8576eb827aa94788b033b60",
          "sha1": "08a4ba759187c65f74c5a6b47b9d53a89a5b392a",
          "md5": "2a55fe2a54927e7fd152169024a7d4f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "settings-v1.0.5-sources.jar",
          "url": "settings-v1.0.5-sources.jar",
          "size": 8656,
          "sha512": "e5c8b1120b147fe7351cdc620fec2f085a8923761b955fee9b757e7f0bc2b63f32361e9c0b7498ed4f9ff76922380e1002c1f9ea254ae1b8a1f83e15757e85a9",
          "sha256": "c7620a6224d04f3138014b14d2f1ce7177b6f6b50695e37063095a99af1a9976",
          "sha1": "9b9490d38fd220164288b2c4a9da52c3bd976d00",
          "md5": "4869a3a4ece6fd1d5f87aa8cb8d6da0d"
        }
      ]
    }
  ]
}
