{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.JavaAsmExtension",
    "module": "analytics-method-return",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "analytics-object-creation",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "analytics-method-return-1.0.jar",
          "url": "analytics-method-return-1.0.jar",
          "size": 8609,
          "sha512": "2eb7d82075d4bd7a828b04181086a0aeb285e3146f58321961ad9e54d0dac8eefc47fad3b4a1d62f0baef7fc67abb2a52f9eb25ae2c9a0772624a99d54d4c9e3",
          "sha256": "e226242e1f33f58150a08b188fce848c57b78ef03cdbf292ccc950094aad3ac8",
          "sha1": "4a9642b16330768bce26012ea5b0395cb77fb3d5",
          "md5": "0b53157c3180f56ec7cdea3cd2acf59d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "com.github.Zelaux.JavaAsmExtension",
          "module": "analytics-object-creation",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "analytics-method-return-1.0.jar",
          "url": "analytics-method-return-1.0.jar",
          "size": 8609,
          "sha512": "2eb7d82075d4bd7a828b04181086a0aeb285e3146f58321961ad9e54d0dac8eefc47fad3b4a1d62f0baef7fc67abb2a52f9eb25ae2c9a0772624a99d54d4c9e3",
          "sha256": "e226242e1f33f58150a08b188fce848c57b78ef03cdbf292ccc950094aad3ac8",
          "sha1": "4a9642b16330768bce26012ea5b0395cb77fb3d5",
          "md5": "0b53157c3180f56ec7cdea3cd2acf59d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "analytics-method-return-1.0-sources.jar",
          "url": "analytics-method-return-1.0-sources.jar",
          "size": 3492,
          "sha512": "507177e54b99762e6b45a7df694851e5a8cded6d0dc41f7fedd8bf0453e91d6740dc7f2c8da624d603b83a0350abd27cb87a870054248a346ab7bd5af76a7ced",
          "sha256": "e0448147949bee7e8b79f149fc1f07a5f47714ec24d84e5f27ed78e739e65c25",
          "sha1": "db6d50eedf4d001ecd7f0454324254b4ac36deba",
          "md5": "7422201f747f924c12d585693f13477d"
        }
      ]
    }
  ]
}
