{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "utils-refs",
    "version": "v1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "utils-refs-v1.0.5.jar",
          "url": "utils-refs-v1.0.5.jar",
          "size": 5818,
          "sha512": "65a3801fefe2d466f7a33bf396bb1ba1f6549dd62fbbba12fd93ff8e382b2148284406eb2dd5d6749b9aae84af55f9b696d8c164079f9396a05b81ac671b412f",
          "sha256": "ecfab58dde77290d7fe40530a2a105b3de6f451ec2de24d973783c6a1a56da79",
          "sha1": "0a4d6765aeab76ec2bbc18863a7b555d645ed244",
          "md5": "c9ec0b701d3a21f17a78478b822be37d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-refs-v1.0.5.jar",
          "url": "utils-refs-v1.0.5.jar",
          "size": 5818,
          "sha512": "65a3801fefe2d466f7a33bf396bb1ba1f6549dd62fbbba12fd93ff8e382b2148284406eb2dd5d6749b9aae84af55f9b696d8c164079f9396a05b81ac671b412f",
          "sha256": "ecfab58dde77290d7fe40530a2a105b3de6f451ec2de24d973783c6a1a56da79",
          "sha1": "0a4d6765aeab76ec2bbc18863a7b555d645ed244",
          "md5": "c9ec0b701d3a21f17a78478b822be37d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-refs-v1.0.5-sources.jar",
          "url": "utils-refs-v1.0.5-sources.jar",
          "size": 1041,
          "sha512": "c60939fec4913704a9302e9a50997179913a864cc15bcff50fe7a1b833a74d18effa2628f9d520dd448433e2c6b96231bf5267467bfb65ed405085fb0ac77f38",
          "sha256": "762ae704887677dd36bc4e6f85e0a0b783742d7c5471f3e1c13d2fb7fb5af29b",
          "sha1": "eb44ddae1310cdd851e350d89b1e1246cbc76e1c",
          "md5": "883113ee892928d4be11d27f40862202"
        }
      ]
    }
  ]
}
