{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.ArcLibrary",
    "module": "ui-tooltips",
    "version": "v1.0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooltips-v1.0.3.1.jar",
          "url": "ui-tooltips-v1.0.3.1.jar",
          "size": 12187,
          "sha512": "e4f9e374636ec4e9438a21ecf0c7c9c1583c2f84ed15090f667ab43bd45f04352b0dd42ebec4581b5b9bb43c2120c80e8c5b77f858235785d15167ebc9aaf6f5",
          "sha256": "59599f8323fba94200718e526a880bea0ab5b0025a28ace1a113fd38f5477b98",
          "sha1": "cc76f0a1c1fca33897ac641df7e0d62df0fed899",
          "md5": "abfeb65ebe151b3aa3367bd0a2b56396"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooltips-v1.0.3.1.jar",
          "url": "ui-tooltips-v1.0.3.1.jar",
          "size": 12187,
          "sha512": "e4f9e374636ec4e9438a21ecf0c7c9c1583c2f84ed15090f667ab43bd45f04352b0dd42ebec4581b5b9bb43c2120c80e8c5b77f858235785d15167ebc9aaf6f5",
          "sha256": "59599f8323fba94200718e526a880bea0ab5b0025a28ace1a113fd38f5477b98",
          "sha1": "cc76f0a1c1fca33897ac641df7e0d62df0fed899",
          "md5": "abfeb65ebe151b3aa3367bd0a2b56396"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-tooltips-v1.0.3.1-sources.jar",
          "url": "ui-tooltips-v1.0.3.1-sources.jar",
          "size": 1752,
          "sha512": "52f2e01914b6831ef59ea639061f9fe1f20651db3655db268a7471bbfb45911f20b2fa12bcbd397d2b814863d03aa7b89e019dc7108ff8cea1d7168b8cde68ee",
          "sha256": "0a1ea9656b96546ebd79f29da84c08014338ed19f79e185d2d9653c27650bb20",
          "sha1": "8d8b03f195a3298e1955dec5c53bf29eb80dbd8f",
          "md5": "819d05fe3694b8128d01489570cb0b21"
        }
      ]
    }
  ]
}
