{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.MindustryModCore",
    "module": "tiledStructures",
    "version": "repo-test1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "tiledStructures-repo-test1.jar",
          "url": "tiledStructures-repo-test1.jar",
          "size": 158182,
          "sha512": "e1e1a181939c373af43a92d3a1cd8eef33b5589b725b077c9176f86fdbc3fff688e9804df4a4dd1021b7df890cc1a71481f459e4a2c464ffe517a3316fa6c526",
          "sha256": "67b531aaee7966de13f44e05135eec60223729ef8bbd27cdc1f570f35602852c",
          "sha1": "386b04c7580a6a45bd8c3683079b3c214bb06325",
          "md5": "453bc4779d0bbccda669c391d6bac2c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.MindustryModCore",
          "module": "core",
          "version": {
            "requires": "repo-test1"
          }
        },
        {
          "group": "com.github.Zelaux.MindustryModCore",
          "module": "graphics",
          "version": {
            "requires": "repo-test1"
          }
        }
      ],
      "files": [
        {
          "name": "tiledStructures-repo-test1.jar",
          "url": "tiledStructures-repo-test1.jar",
          "size": 158182,
          "sha512": "e1e1a181939c373af43a92d3a1cd8eef33b5589b725b077c9176f86fdbc3fff688e9804df4a4dd1021b7df890cc1a71481f459e4a2c464ffe517a3316fa6c526",
          "sha256": "67b531aaee7966de13f44e05135eec60223729ef8bbd27cdc1f570f35602852c",
          "sha1": "386b04c7580a6a45bd8c3683079b3c214bb06325",
          "md5": "453bc4779d0bbccda669c391d6bac2c5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiledStructures-repo-test1-sources.jar",
          "url": "tiledStructures-repo-test1-sources.jar",
          "size": 20793,
          "sha512": "8cb513d40934d6dc85df2f640aa2e7e4ad447a98efd053d7f89765044c73af7355e800b8fe98dac45dae2df4f60c153be8f1195d256f534d03b3609180f38b1b",
          "sha256": "489e6df38714a97559d79282f6eaff6eba7bb9075fb5a774053486c873c7344d",
          "sha1": "509e592902a1e494347e6ffb0c673389ccb01ec9",
          "md5": "0b7cd626f9dbbbec5e0b318d6fba77b2"
        },
        {
          "name": "tiledStructures-repo-test1-sources.jar",
          "url": "tiledStructures-repo-test1-sources.jar",
          "size": 20793,
          "sha512": "8cb513d40934d6dc85df2f640aa2e7e4ad447a98efd053d7f89765044c73af7355e800b8fe98dac45dae2df4f60c153be8f1195d256f534d03b3609180f38b1b",
          "sha256": "489e6df38714a97559d79282f6eaff6eba7bb9075fb5a774053486c873c7344d",
          "sha1": "509e592902a1e494347e6ffb0c673389ccb01ec9",
          "md5": "0b7cd626f9dbbbec5e0b318d6fba77b2"
        }
      ]
    }
  ]
}
