{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.MindustryModCore",
    "module": "customBlockShape",
    "version": "repo-test1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customBlockShape-repo-test1.jar",
          "url": "customBlockShape-repo-test1.jar",
          "size": 109215,
          "sha512": "bf5fd587f833a04db5eb65c84fd15198da01cb22016a71e051cb11f7d11d974f6821fe7963e0470f45955520a24991cf67ba75958822eb2e9b3a96663094b2a6",
          "sha256": "8cd9081475a1a8158718ca17c621ad7354b69a7280ad92a857a74a6cfde36810",
          "sha1": "5c6631cdad577337d4e5e4b3d5e296253f7fc4f0",
          "md5": "31601c3f3fb4a546c6fb4bb7eb988fd0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.MindustryModCore",
          "module": "core",
          "version": {
            "requires": "repo-test1"
          }
        },
        {
          "group": "com.github.Zelaux.MindustryModCore",
          "module": "utils",
          "version": {
            "requires": "repo-test1"
          }
        }
      ],
      "files": [
        {
          "name": "customBlockShape-repo-test1.jar",
          "url": "customBlockShape-repo-test1.jar",
          "size": 109215,
          "sha512": "bf5fd587f833a04db5eb65c84fd15198da01cb22016a71e051cb11f7d11d974f6821fe7963e0470f45955520a24991cf67ba75958822eb2e9b3a96663094b2a6",
          "sha256": "8cd9081475a1a8158718ca17c621ad7354b69a7280ad92a857a74a6cfde36810",
          "sha1": "5c6631cdad577337d4e5e4b3d5e296253f7fc4f0",
          "md5": "31601c3f3fb4a546c6fb4bb7eb988fd0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "customBlockShape-repo-test1-sources.jar",
          "url": "customBlockShape-repo-test1-sources.jar",
          "size": 7117,
          "sha512": "115775b1ad36074ecff81cd3b5416ca93294447790191c327856724edfef858d219b3d183bc56f3c854dc86d444b8b9405fabf318957b65c526d0db83b5a24ba",
          "sha256": "583863fd76a04b554b7d54f197e6af3ed4afbd9c3978a3f4919708f2124038ec",
          "sha1": "4b909d442184859597711c98915221f8d36d4a03",
          "md5": "3524cdc299e779ebda3e481e15f8da82"
        },
        {
          "name": "customBlockShape-repo-test1-sources.jar",
          "url": "customBlockShape-repo-test1-sources.jar",
          "size": 7117,
          "sha512": "115775b1ad36074ecff81cd3b5416ca93294447790191c327856724edfef858d219b3d183bc56f3c854dc86d444b8b9405fabf318957b65c526d0db83b5a24ba",
          "sha256": "583863fd76a04b554b7d54f197e6af3ed4afbd9c3978a3f4919708f2124038ec",
          "sha1": "4b909d442184859597711c98915221f8d36d4a03",
          "md5": "3524cdc299e779ebda3e481e15f8da82"
        }
      ]
    }
  ]
}
