{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.Zelaux.MindustryModCore",
    "module": "customBlockShape",
    "version": "repo-test1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customBlockShape-repo-test1.jar",
          "url": "customBlockShape-repo-test1.jar",
          "size": 109215,
          "sha512": "6d169aa1d1d09767df352c4afb4b4cb0a65b072240cb6c330923e1911652921bb9583a79ce5dcc2680081b1f4ee00928f8d4454d351d75ee451f350d07565c36",
          "sha256": "9fdd0064aa9f30b33178256061cfeb0838c2f454e9b726e0e3345e56e20c7ec5",
          "sha1": "39ae6909f93d5c9055f53e7fcc17166f37a2bbc9",
          "md5": "d248d8424e5219003d25b709c351dc0f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Zelaux.MindustryModCore",
          "module": "core",
          "version": {
            "requires": "repo-test1"
          }
        },
        {
          "group": "com.github.Zelaux.MindustryModCore",
          "module": "utils",
          "version": {
            "requires": "repo-test1"
          }
        }
      ],
      "files": [
        {
          "name": "customBlockShape-repo-test1.jar",
          "url": "customBlockShape-repo-test1.jar",
          "size": 109215,
          "sha512": "6d169aa1d1d09767df352c4afb4b4cb0a65b072240cb6c330923e1911652921bb9583a79ce5dcc2680081b1f4ee00928f8d4454d351d75ee451f350d07565c36",
          "sha256": "9fdd0064aa9f30b33178256061cfeb0838c2f454e9b726e0e3345e56e20c7ec5",
          "sha1": "39ae6909f93d5c9055f53e7fcc17166f37a2bbc9",
          "md5": "d248d8424e5219003d25b709c351dc0f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "customBlockShape-repo-test1-sources.jar",
          "url": "customBlockShape-repo-test1-sources.jar",
          "size": 7117,
          "sha512": "379833fec1ce0862c2938e4ab2b0585eb1661a7e6e33ad6c25f804956cb4f2e94d0f5ca9e90d95583dae3ed742cf3926e1f1d3d1e94aeac4347d15866367ab59",
          "sha256": "0dea905e65226d8ea205226a255eb4beb54019230a186c02d1d407ee65f83738",
          "sha1": "64c84ca8a008454d2aa6f9585c639d7f9dec70bb",
          "md5": "a190a099147d346ce3d62353eff15e46"
        },
        {
          "name": "customBlockShape-repo-test1-sources.jar",
          "url": "customBlockShape-repo-test1-sources.jar",
          "size": 7117,
          "sha512": "379833fec1ce0862c2938e4ab2b0585eb1661a7e6e33ad6c25f804956cb4f2e94d0f5ca9e90d95583dae3ed742cf3926e1f1d3d1e94aeac4347d15866367ab59",
          "sha256": "0dea905e65226d8ea205226a255eb4beb54019230a186c02d1d407ee65f83738",
          "sha1": "64c84ca8a008454d2aa6f9585c639d7f9dec70bb",
          "md5": "a190a099147d346ce3d62353eff15e46"
        }
      ]
    }
  ]
}
